### PR TITLE
Remove doc-filter after query switched to unified syntax

### LINKED ISSUE #737: Error when running jobs using -f on command line
### Description

When I use `python project.py run -f ...` on the command line, flow errors internally.

### To reproduce

```python
import signac
from flow import FlowProject

from pathlib import Path

project = signac.get_project(Path(__file__).parent / "SignacProject")

job_sps = [{'a': 1, 'b': 2},
           {'a': 1, 'b': 3}]

for job_sp in job_sps:
    job = project.open_job(job_sp)
    job.init()


class SignacProject(FlowProject):
    pass


@SignacProject.operation
def print_statepoint(job):
    print(job.sp)


if __name__ == "__main__":
    SignacProject.get_project(project.path).main()
```

Try to run the only job on the command line with

```bash
python script.py run -f b 2
```

### Error output

```bash
$ python script.py run -f b 2
Using environment configuration: StandardEnvironment
Interpreted filter arguments as '{"b": 2}'.
Traceback (most recent call last):
  File "/Users/tomwalt/scripts/signac/flow-2.0-bug/script.py", line 26, in <module>
    SignacProject.get_project(project.path).main()
  File "/Users/tomwalt/miniconda3/envs/py310/lib/python3.10/site-packages/flow/project.py", line 5132, in main
    args.func(args)
  File "/Users/tomwalt/miniconda3/envs/py310/lib/python3.10/site-packages/flow/project.py", line 4820, in _main_run
    aggregates = self._select_jobs_from_args(args)
  File "/Users/tomwalt/miniconda3/envs/py310/lib/python3.10/site-packages/flow/project.py", line 4908, in _select_jobs_from_args
    return _JobAggregateCursor(self, filter_, doc_filter)
TypeError: _JobAggregateCursor.__init__() takes from 2 to 3 positional arguments but 4 were given
```

### System configuration

Please complete the following information:

 - Operating System [e.g. macOS]: macOS, linux
 - Version of Python [e.g. 3.7]: 3.10.10
 - Version of signac [e.g. 1.0]: 2.0.0
 - Version of signac-flow: 0.25.0

### PR DESCRIPTION
**Pull request by cbkerr**
## Motivation and Context

Resolves #737 

See also https://github.com/glotzerlab/signac/pull/516

However, this conflicts with something [in the changelog](https://github.com/glotzerlab/signac/blob/1472dfa3037c0622b1869c9d3b0479ed8e0fa4f6/changelog.txt#L150):
"Deprecated ``doc_filter`` arguments, which are replaced by namespaced filters. Due to their long history, ``doc_filter`` arguments will still be accepted in signac 2.0 and will only be removed in 3.0 (#516)."

## Checklist:

- [x] I am familiar with the [Contributing Guidelines](https://github.com/glotzerlab/signac-flow/blob/main/CONTRIBUTING.md).
- [x] I agree with the terms of the [Contributor Agreement](https://github.com/glotzerlab/signac-flow/blob/main/ContributorAgreement.md).
- [x] My name is on the [list of contributors](https://github.com/glotzerlab/signac-flow/blob/main/contributors.yaml).
- [x] The changes introduced by this pull request are covered by existing or newly introduced tests.
- [x] The [package documentation](https://github.com/glotzerlab/signac-flow/tree/main/doc) and [framework documentation](https://docs.signac.io/) in [signac-docs](https://github.com/glotzerlab/signac-docs) are up to date with these changes.
- [x] I have updated the [changelog](https://github.com/glotzerlab/signac-flow/blob/main/changelog.txt) and added any related issue and pull request numbers for future reference.

### CODE REVIEW

**Review by bdice — APPROVED** [review]
Changes look good to me. The changelog you mentioned should be updated -- we removed doc filters in 2.0 and chose not to wait until 3.0. Can you file a PR for that?

I suppose this code path wasn't being run by tests. It would be good to add a test for filtering on the command line.

**Comment by bdice** [comment]
I opened a PR to fix signac's changelog: https://github.com/glotzerlab/signac/pull/916

**Comment by cbkerr** [comment]
@bdice I added a test and confirmed that it fails without the change introduced by this PR

**Review by tommy-waltmann — APPROVED** [review]
Thanks for the fix!

**Pull request merged**
