### PR TITLE
Fix issue #343.

### PR DESCRIPTION
**Pull request by csadorf**
## Description

Fixes issue #343 .

## Motivation and Context

See issue description.

## Types of Changes

- [ ] Documentation update
- [x] Bug fix
- [ ] New feature
- [ ] Breaking change<sup>1</sup>

<sup>1</sup>The change breaks (or has the potential to break) existing functionality.

## Checklist:

- [x] I am familiar with the [**Contributing Guidelines**](https://github.com/glotzerlab/signac-flow/blob/master/CONTRIBUTING.md).
- [x] I agree with the terms of the [**Contributor Agreement**](https://github.com/glotzerlab/signac-flow/blob/master/ContributorAgreement.md).
- [x] My name is on the [list of contributors](https://github.com/glotzerlab/signac-flow/blob/master/contributors.yaml).
- [x] My code follows the [code style guideline](https://github.com/glotzerlab/signac-flow/blob/master/CONTRIBUTING.md#code-style) of this project.
- [x] The changes introduced by this pull request are covered by existing or newly introduced tests.

If necessary:
- [ ] I have updated the API documentation as part of the package doc-strings.
- [ ] I have created a separate pull request to update the [framework documentation](https://docs.signac.io/) on [signac-docs](https://github.com/glotzerlab/signac-docs) and linked it here.
- [ ] I have updated the [changelog](https://github.com/glotzerlab/signac-flow/blob/master/changelog.txt).

### CODE REVIEW

**Comment by bdice** [comment]
@csadorf Can you provide a bit more detail on the purpose and content of this PR? Does this PR require #344 to be merged into the main branch? What is needed to make tests pass?

**Comment by bdice** [comment]
I marked this as ready for review based on this comment: https://github.com/glotzerlab/signac-flow/issues/343#issuecomment-693473081. However,
1. This PR does not appear to contain the fix from commit https://github.com/glotzerlab/signac-flow/pull/344/commits/d2f6cb01661779d605a9b803c9fb40c04e805563. Is this an oversight?
2. Tests are failing -- I think this is related to aggregation changes that have happened since 0.10.0 (the hotfix was developed for 0.10.0 and released as 0.10.1).

**Comment by b-butler** [comment]
@csadorf Any news on this?

**Comment by csadorf** [comment]
Verified that unit tests fail without the fix: https://app.circleci.com/pipelines/github/glotzerlab/signac-flow/1569/workflows/727eae0e-4214-4e4d-9c08-daa6799eebd0/jobs/10835

**Review by bdice — APPROVED** [review]
This looks good to me. I have also looked at the hotfix that went into 0.10.1.

**Comment by csadorf** [comment]
This should be ready for review and merge after tests have passed.

**Pull request merged**
