### PR TITLE
Add legend for scheduler status symbols.

### PR DESCRIPTION
**Pull request by csadorf**
Fixes issue #39.

### CODE REVIEW

**Comment by csadorf** [comment]
@bdice You created issue #39 initially, does this patch resolve the issue?

**Comment by bdice** [comment]
@csadorf I get some crazy recursion error when calling `python project.py status` with this branch of flow. I am running a fresh installation of `flow` from source and a fresh installation of `signac-flow-glotzer-environments` on Flux. I think this is unrelated to your changes, but may need a bugfix. Purely from looking at the code, it looks like this PR will do what I wanted it to do.

```python
Traceback (most recent call last):
  File "project.py", line 86, in <module>
    Project().main()
  File "/home/bdice/code/signac-flow/flow/project.py", line 2629, in main
    self._environment.add_args(env_group)
  File "/home/bdice/code/signac-flow-glotzer-environments/glotzer_environments/glotzer_environments.py", line 51, in add_args
    super(GlotzerFluxEnvironment, cls).add_args(parser)
  File "/home/bdice/code/signac-flow/flow/environment.py", line 276, in add_args
    super(DefaultTorqueEnvironment, cls).add_args(parser)
  File "/home/bdice/miniconda3/envs/dice/lib/python3.7/site-packages/deprecation.py", line 247, in _inner
    return function(*args, **kwargs)
  File "/home/bdice/code/signac-flow/flow/legacy_templating.py", line 353, in add_args
    super(cls, cls).add_args(parser)
  File "/home/bdice/code/signac-flow/flow/environment.py", line 276, in add_args
    super(DefaultTorqueEnvironment, cls).add_args(parser)
  File "/home/bdice/miniconda3/envs/dice/lib/python3.7/site-packages/deprecation.py", line 247, in _inner
    return function(*args, **kwargs)

... infinite recursion ...

  File "/home/bdice/miniconda3/envs/dice/lib/python3.7/site-packages/deprecation.py", line 247, in _inner
    return function(*args, **kwargs)
  File "/home/bdice/code/signac-flow/flow/legacy_templating.py", line 353, in add_args
    super(cls, cls).add_args(parser)
  File "/home/bdice/code/signac-flow/flow/environment.py", line 276, in add_args
    super(DefaultTorqueEnvironment, cls).add_args(parser)
  File "/home/bdice/miniconda3/envs/dice/lib/python3.7/site-packages/deprecation.py", line 243, in _inner
    removed_in, details)
  File "/home/bdice/miniconda3/envs/dice/lib/python3.7/site-packages/deprecation.py", line 59, in __init__
    super(DeprecatedWarning, self).__init__(function, deprecated_in,
RecursionError: maximum recursion depth exceeded while calling a Python object
```

**Comment by csadorf** [comment]
I saw something similar earlier while trying to debug an unrelated issue. I think this is related to some bug in the glotzer_environment, not this patch.

**Comment by csadorf** [comment]
@bdice I think I identified the problem and fixed it as part of PR #80 . Could you test whether the issue is resolved?

**Pull request merged**
