### PR TITLE
Fix issue #758.

### LINKED ISSUE #758: Conflicting Namespace- Using the SLURM scheduler to check the status of a project tries to find bundled operations from other users and/or instances of FlowProject
### Description

When submitting jobs using the default SLURM template to a scheduler, the job status is returned with the [A], [Q], etc. progress to keep track of these jobs. The jobs themselves are labeled in the scheduler via their NAME attribute, which looks something like `Project_name/bundle/job_hash`. The issues arises when two users call their projects the same `Project_name` when creating the `FlowProject` subclass. An error will be raised because the status check sees that there's a job under your project, but that job_hash will not exist in the .bundles directory. A possible solution might be to append the username to the Project_name when the job is posted to the scheduler i.e. `Project_name-user_name/bundle/job_hash`.

### To reproduce

./project1/project1.py
```python
class Project(FlowProject):
    """Subclass of FlowProject to provide custom methods and attributes."""
    def __init__(self):
        super().__init__()
if __name__ == "__main__":
    Project().main()
```

./project2/project2.py
```python
class Project(FlowProject):
    """Subclass of FlowProject to provide custom methods and attributes."""
    def __init__(self):
        super().__init__()
if __name__ == "__main__":
    Project().main()
```

```bash
python project1.py submit 
cd ../project2
python project2.py status
```

### Error output

```
(membrane) [quachcd@head minimized_surfaces]$ python src/project.py status 
/raid6/homes/quachcd/.conda/envs/membrane/lib/python3.10/site-packages/pkg_resources/__init__.py:121: DeprecationWarning: pkg_resources is deprecated as an API
  warnings.warn("pkg_resources is deprecated as an API", DeprecationWarning)
/raid6/homes/quachcd/.conda/envs/membrane/lib/python3.10/site-packages/pkg_resources/__init__.py:2870: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('mpl_toolkits')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/raid6/homes/quachcd/.conda/envs/membrane/lib/python3.10/site-packages/pkg_resources/__init__.py:2870: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/raid6/homes/quachcd/Documents/env/science_env/mbuild/mbuild/recipes/__init__.py:13: DeprecationWarning: SelectableGroups dict interface is deprecated. Use select.
  entry_points = metadata.entry_points()["mbuild.plugins"]
/raid6/homes/quachcd/Documents/env/science_env/gmso/gmso/formats/mol2.py:79: UserWarning: The record type indicator Meta is not supported. Skipping current section and moving to the next RTI header.
  warnings.warn(
/raid6/homes/quachcd/Documents/env/science_env/gmso/gmso/formats/mol2.py:79: UserWarning: The record type indicator @<TRIPOS>SUBSTRUCTURE is not supported. Skipping current section and moving to the next RTI header.
  warnings.warn(
Using environment configuration: Rahman
WARNING:flow.project:Unable to load template from package. Original Error '__main__.__spec__ is None'.
Querying scheduler...
ERROR:flow.project:Error during status update: [Errno 2] No such file or directory: '/raid6/homes/quachcd/Documents/science/membrane/solvents-separation-membrane/screening_workflow/minimized_surfaces/.bundles/Project/bundle/9bbc851ef6ac321ec66fe0a8d7c94d735673411d'
Use '--ignore-errors' to complete the update anyways.
Traceback (most recent call last):
  File "/raid6/homes/quachcd/Documents/science/membrane/solvents-separation-membrane/screening_workflow/minimized_surfaces/src/project.py", line 227, in <module>
    project.main()
  File "/raid6/homes/quachcd/.conda/envs/membrane/lib/python3.10/site-packages/flow/project.py", line 5120, in main
    args.func(args)
  File "/raid6/homes/quachcd/.conda/envs/membrane/lib/python3.10/site-packages/flow/project.py", line 4767, in _main_status
    raise error
  File "/raid6/homes/quachcd/.conda/envs/membrane/lib/python3.10/site-packages/flow/project.py", line 4761, in _main_status
    self.print_status(jobs=aggregates, **args)
  File "/raid6/homes/quachcd/.conda/envs/membrane/lib/python3.10/site-packages/flow/project.py", line 2980, in print_status
    status_results, job_labels, individual_jobs = self._fetch_status(
  File "/raid6/homes/quachcd/.conda/envs/membrane/lib/python3.10/site-packages/flow/project.py", line 2646, in _fetch_status
    scheduler_info = self._query_scheduler_status(
  File "/raid6/homes/quachcd/.conda/envs/membrane/lib/python3.10/site-packages/flow/project.py", line 2554, in _query_scheduler_status
    return {
  File "/raid6/homes/quachcd/.conda/envs/membrane/lib/python3.10/site-packages/flow/project.py", line 2554, in <dictcomp>
    return {
  File "/raid6/homes/quachcd/.conda/envs/membrane/lib/python3.10/site-packages/flow/project.py", line 2198, in scheduler_jobs
    yield from self._expand_bundled_jobs(scheduler.jobs())
  File "/raid6/homes/quachcd/.conda/envs/membrane/lib/python3.10/site-packages/flow/project.py", line 2172, in _expand_bundled_jobs
    with open(self._fn_bundle(job.name())) as file:
FileNotFoundError: [Errno 2] No such file or directory: '/raid6/homes/quachcd/Documents/science/membrane/solvents-separation-membrane/screening_workflow/minimized_surfaces/.bundles/Project/bundle/9bbc851ef6ac321ec66fe0a8d7c94d735673411d'
```

### System configuration

Please complete the following information:

 - Operating System: Linux-4.18.0-372.26.1.el8_6.x86_64-x86_64-with-glibc2.10
 - Version of Python=3.8.15
 - Version of signac=2.0.0
 - Version of signac-flow=0.25.1

### PR DESCRIPTION
**Pull request by bdice**
## Description
This PR attempts to fix #758.

## Motivation and Context
Currently bundles are considered for status check operations as long as they start with a given prefix. This prefix is not uniquely identifying (through the inclusion of a hash, for example), because it is meant to be short and readable. However, this can cause projects to try to read status updates from other FlowProject instances (and potentially other users) if they share a common FlowProject class name.

This fixes #758 by only considering bundles that already exist within the project.

Note: These bundle ids are guaranteed to be unique (up to hash collisions) because they include the project's filesystem path in a hash when computing the id of each `_JobOperation`. These `_JobOperation` ids are then hashed together to produce a unique bundle id.

I do not have a way to test this PR on a scheduler. Support from reviewers in testing would be welcome.

## Checklist:
- [x] I am familiar with the [Contributing Guidelines](https://github.com/glotzerlab/signac-flow/blob/main/CONTRIBUTING.md).
- [x] I agree with the terms of the [Contributor Agreement](https://github.com/glotzerlab/signac-flow/blob/main/ContributorAgreement.md).
- [x] My name is on the [list of contributors](https://github.com/glotzerlab/signac-flow/blob/main/contributors.yaml).
- [ ] The changes introduced by this pull request are covered by existing or newly introduced tests.
- [x] The [package documentation](https://github.com/glotzerlab/signac-flow/tree/main/doc) and [framework documentation](https://docs.signac.io/) in [signac-docs](https://github.com/glotzerlab/signac-docs) are up to date with these changes.
- [ ] I have updated the [changelog](https://github.com/glotzerlab/signac-flow/blob/main/changelog.txt) and added any related issue and pull request numbers for future reference.

### CODE REVIEW

**Review by joaander — APPROVED** [review]
Thanks! This turned out to be a simple fix.

As you say, we should test on a cluster before merging.

**Comment by CalCraven** [comment]
Tested this using the example I posted in #758. Works like a charm, thanks @bdice!

**Comment by bdice** [comment]
Great. @cbkerr I'll let you merge since you're taking care of the release in #833. Please add a changelog entry in the release PR.

**Comment by cbkerr** [comment]
@CalCraven Thanks for testing! I'll put it in the release

**Pull request merged**
