### PR TITLE
Optimization: Don't use min_len_unique_id in str(_JobOperation).

### PR DESCRIPTION
**Pull request by bdice**
## Description
Don't call `Project.min_len_unique_id` when converting `_JobOperation` to a string (presumably for logging or script generation). It's O(N) and is called O(N) times, leading to O(N^2) behavior and significant performance penalties.

Related to https://github.com/glotzerlab/signac/pull/434.

The regression was introduced in #334. **This does not need a changelog line because the code where the regression was introduced has not been released.**

## Motivation and Context
In the "run" benchmarks I'm using (1000 jobs, 3 operations with preconditions/postconditions, 2 labels), `min_len_unique_id` takes 19.4 seconds out of a total runtime of 37.8 seconds (over 50%!). Removing this call and printing the full job id decreases the total runtime to 18.1 seconds.

The performance cost of this call may also be reduced by PR #396, if the `__str__` method of `_JobOperation` is called less frequently.

### Profile before:
image

### Profile after:
image

(There is a tiny, tiny highlighted pink sliver on the right side. That's the `__str__` operation without the expensive call to `min_len_unique_id`.)

## Types of Changes

- [ ] Documentation update
- [x] Bug fix
- [ ] New feature
- [ ] Breaking change<sup>1</sup>

<sup>1</sup>The change breaks (or has the potential to break) existing functionality.

## Checklist:
- [x] I am familiar with the [**Contributing Guidelines**](https://github.com/glotzerlab/signac-flow/blob/master/CONTRIBUTING.md).
- [x] I agree with the terms of the [**Contributor Agreement**](https://github.com/glotzerlab/signac-flow/blob/master/ContributorAgreement.md).
- [x] My name is on the [list of contributors](https://github.com/glotzerlab/signac-flow/blob/master/contributors.yaml).
- [x] My code follows the [code style guideline](https://github.com/glotzerlab/signac-flow/blob/master/CONTRIBUTING.md#code-style) of this project.
- [x] The changes introduced by this pull request are covered by existing or newly introduced tests.

If necessary:
- [ ] I have updated the API documentation as part of the package doc-strings.
- [ ] I have created a separate pull request to update the [framework documentation](https://docs.signac.io/) on [signac-docs](https://github.com/glotzerlab/signac-docs) and linked it here.
- [ ] I have updated the [changelog](https://github.com/glotzerlab/signac-flow/blob/master/changelog.txt).

### CODE REVIEW

**Comment by atravitz** [comment]
This looks very worthwhile to me! Was the reason for this in the first place just for concise output?

**Comment by cbkerr** [comment]
Looks good to me too

**Review by b-butler — APPROVED** [review]
LGTM

**Comment by bdice** [comment]
@atravitz Yes, it was just used for concise output.

**Pull request merged**
