### PR TITLE
Implement the "fork" directive.

### PR DESCRIPTION
**Pull request by csadorf**
## Description

If the "fork" directive is True, operations are always executed within a
subprocess even if they could be called directly.

## Motivation and Context

This is useful whenever certain parallelization schemes must be executed
within a nondaemonic process, e.g., `multiprocessing.Pool`.

## Types of Changes

- [ ] Documentation update
- [ ] Bug fix
- [x] New feature
- [ ] Breaking change<sup>1</sup>

<sup>1</sup>The change breaks (or has the potential to break) existing functionality.

## Checklist:

- [x] I am familiar with the [**Contributing Guidelines**](https://github.com/glotzerlab/signac-flow/blob/master/CONTRIBUTING.md).
- [x] I agree with the terms of the [**Contributor Agreement**](https://github.com/glotzerlab/signac-flow/blob/master/ContributorAgreement.md).
- [x] My name is on the [list of contributors](https://github.com/glotzerlab/signac-flow/blob/master/contributors.yaml).
- [x] My code follows the [code style guideline](https://github.com/glotzerlab/signac-flow/blob/master/CONTRIBUTING.md#code-style) of this project.
- [ ] The changes introduced by this pull request are covered by existing or newly introduced tests.

If necessary:
- [ ] I have updated the API documentation as part of the package doc-strings.
- [ ] I have created a separate pull request to update the [framework documentation](https://docs.signac.io/) on [signac-docs](https://github.com/glotzerlab/signac-docs) and linked it here.
- [x] I have updated the [changelog](https://github.com/glotzerlab/signac-flow/blob/master/changelog.txt).

### CODE REVIEW

**Comment by vyasr** [comment]
I think the meaningful test would be to define a function that requires forking (e.g. one using a Pool), testing that it fails if you put it in a normal operation, and then testing that it succeeds if you put it in a forked operation.

**Comment by csadorf** [comment]
I'm still not 100% convinced that introducing a new top-level decorator is the way to go here. Maybe overkill?

**Comment by csadorf** [comment]
@bdice @vyasr I've implemented a unit test and also enabled the specification of a condition-function (as a function of job). That makes it easier to only fork under specific conditions.

**Comment by csadorf** [comment]
There seems to be some issue import issue, which causes the unit tests to fail non-deterministically. I'm investigating.

**Comment by csadorf** [comment]
@bdice @vyasr Ready for merge.

**Comment by vyasr** [comment]
LGTM. Regarding whether a top-level directive is necessary, what else would you suggest? Or do you simply question whether users need this power at all? It certainly seems useful/necessary in some cases.

**Comment by csadorf** [comment]
> LGTM.

Anything you would like to resolve before approving this PR?

> Regarding whether a top-level directive is necessary, what else would you suggest? Or do you simply question whether users need this power at all? It certainly seems useful/necessary in some cases.

No, I just don't like introducing top-level items into the root namespace when we are not 100% sure yet how it fits in. Even as part of this PR we switched between making it a directive and making it a top-level function.

**Comment by vyasr** [comment]
I appreciate that concern; what might you suggest as an alternative in this case? Might as well discuss properly now before we merge the PR and are forced to support it for backwards compatibility.

I think this information needs to be available at the level of executing an operation, and directives are the most natural method in flow for attaching metadata to an operation. Providing a top-level function seems less natural to use, and possibly even an anti-pattern from a user perspective, no?

**Comment by csadorf** [comment]
@vyasr I think you were not present for this discussion. At one of the last sprints we decided that we are going to shift the focus of execution-directives more to "submission directives". Meaning, a lose set of keyword arguments that are interpreted by the templates as a convention and are not otherwise programmatically enforced. That's why we made the `@fork` decorator a top-level function. However, the *executable* directive breaks that pattern, because it *is* utilized by both the templates and the *run* functions.

**Comment by vyasr** [comment]
After a brief conversation with @csadorf, we want to hold off merging until we have another discussion on where exactly this code belongs.

**Comment by csadorf** [comment]
I'm going to reopen this after we have had that discussion.

**Pull request closed without merging**
