### PR TITLE
deprecate progressbar.py

### PR DESCRIPTION
**Pull request by zhou-pj**
deprecate progressbar.py

## Types of Changes

- [ ] Documentation update
- [ ] Bug fix
- [ ] New feature
- [x] Breaking change<sup>1</sup>

<sup>1</sup>The change breaks (or has the potential to break) existing functionality.

## Checklist:

- [x] I am familiar with the [**Contributing Guidelines**](https://github.com/glotzerlab/signac-flow/blob/master/CONTRIBUTING.md).
- [x] I agree with the terms of the [**Contributor Agreement**](https://github.com/glotzerlab/signac-flow/blob/master/ContributorAgreement.md).
- [x] My name is on the [list of contributors](https://github.com/glotzerlab/signac-flow/blob/master/contributors.yaml).
- [x] My code follows the [code style guideline](https://github.com/glotzerlab/signac-flow/blob/master/CONTRIBUTING.md#code-style) of this project.
- [x] The changes introduced by this pull request are covered by existing or newly introduced tests.

If necessary:
- [ ] I have updated the API documentation as part of the package doc-strings.
- [ ] I have created a separate pull request to update the [framework documentation](https://docs.signac.io/) on [signac-docs](https://github.com/glotzerlab/signac-docs) and linked it here.
- [ ] I have updated the [changelog](https://github.com/glotzerlab/signac-flow/blob/master/changelog.txt).

### CODE REVIEW

**Comment by zhou-pj** [comment]
A side note: I also changed the pythonpath in test_project to address bug in testing.

**Comment by vyasr** [comment]
@csadorf I'm able to run this script on the login nodes:

```
import tqdm

for i in tqdm.tqdm(range(int(1e7))):
    pass
```

and it renders the progressbar without error. Is that sufficient to address your concern, or is there something further that needs to be tested?

**Comment by csadorf** [comment]
> @csadorf I'm able to run this script on the login nodes:
> 
> ```
> import tqdm
> 
> for i in tqdm.tqdm(range(int(1e7))):
>     pass
> ```
> 
> and it renders the progressbar without error. Is that sufficient to address your concern, or is there something further that needs to be tested?

No, because the status update is in itself parallelized. Can you run the same code within a `multiprocessing.Pool` ?

**Comment by vyasr** [comment]
```
from multiprocessing import Pool
import tqdm
from pbar import with_progressbar

def testfun(i):
    for i in range(int(i*1e7)):
        pass

with Pool(2) as p:
    list(with_progressbar(
        iterable=p.map(testfun, range(8)), desc='test'))
    list(tqdm.tqdm(
        iterable=p.map(testfun, range(8)), desc='test'))
```

I copied your progressbar into `pbar.py` to test this. This script runs, but neither progressbar properly updates live; they just show up when they full iterable has been consumed. That seems like a separate problem than the deprecation this PR is intended to address, though.

For good measure, I also just checked out this branch and tested it on a live project and the status update works fine.

**Comment by csadorf** [comment]
@vyasr This is the code path that prompted me to implement the fallback-progress bar. I recommend that we keep that in place, but use `tqdm` *everywhere* else.

https://github.com/glotzerlab/signac-flow/blob/e18eb6e0c97afc73a3366775b6c68f1ef72fae9c/flow/project.py#L955

**Pull request merged**
