### PR TITLE
Use mistune for terminal output.

### PR DESCRIPTION
**Pull request by csadorf**
Minimal example on how to use mistune for the status terminal output.

This branch requires the following mistune code version: https://github.com/csadorf/mistune/tree/terminal-renderer/mistune

### CODE REVIEW

**Comment by zhou-pj** [comment]
@csadorf The output looks good to me in the minimal example. I'm going to put it to test on the other output styles and see if any issue comes up.

**Comment by vyasr** [comment]
@csadorf @zhou-pj what's the status of this PR? I already see `mistune.text` used in #163, but the template is slightly different. Were these (or equivalent) changes incorporated separately to that PR using https://github.com/csadorf/mistune? If not, should we go ahead and merge this PR? While we're still figuring out how to get our text renderer merged into mistune, at this point I think we are mostly committed to using mistune in general for Markdown rendering.

**Comment by zhou-pj** [comment]
> @csadorf @zhou-pj what's the status of this PR? I already see `mistune.text` used in #163, but the template is slightly different. Were these (or equivalent) changes incorporated separately to that PR using https://github.com/csadorf/mistune? If not, should we go ahead and merge this PR? While we're still figuring out how to get our text renderer merged into mistune, at this point I think we are mostly committed to using mistune in general for Markdown rendering.

I have incorporated all suggestions in this PR to the #163, and has been editing directly in #163 since. Sorry I should have communicated this on here before.

**Comment by vyasr** [comment]
No problem, thanks for the update. I'll close this PR then.

**Pull request closed without merging**
