### PR TITLE
Make bundle_prefix consistent with bundle_id

### LINKED ISSUE #718: Bundling not working with FlowProject subclass
The FlowProject class is not using consistent logic for writing/reading bundle information, which causes problems when using certain subclasses of FlowProject. We should centralize the definition of a bundle prefix in a single place (probably a module constant) and use it as a string template for formatting so we don't have to keep these two code paths in sync.

This bug was identified by @bpuchala - thanks for reporting!

https://github.com/glotzerlab/signac-flow/blob/475b8e416edba5db1dab966335c0a5b8a1cfe108/flow/project.py#L2217

https://github.com/glotzerlab/signac-flow/blob/475b8e416edba5db1dab966335c0a5b8a1cfe108/flow/project.py#L2206

I'm not 100% sure how to test this or if it would require additional mocked logic in our testing framework. I'm inclined to centralize the definition and call that good enough. @bpuchala has confirmed that the proposed fix in https://github.com/bpuchala/signac-flow/commit/c7e8893d46f27b9ab59ea2a4c07208e4e3b7cf16 is sufficient to solve the problem.

### PR DESCRIPTION
**Pull request by bdice**
## Description
Fixes #718. Thanks @bpuchala for identifying the problem!

## Checklist:
- [x] I am familiar with the [Contributing Guidelines](https://github.com/glotzerlab/signac-flow/blob/master/CONTRIBUTING.md).
- [x] I agree with the terms of the [Contributor Agreement](https://github.com/glotzerlab/signac-flow/blob/master/ContributorAgreement.md).
- [x] My name is on the [list of contributors](https://github.com/glotzerlab/signac-flow/blob/master/contributors.yaml).
- [ ] The changes introduced by this pull request are covered by existing or newly introduced tests.
- [x] The [package documentation](https://github.com/glotzerlab/signac-flow/tree/master/doc) and [framework documentation](https://docs.signac.io/) in [signac-docs](https://github.com/glotzerlab/signac-docs) are up to date with these changes.
- [x] I have updated the [changelog](https://github.com/glotzerlab/signac-flow/blob/master/changelog.txt) and added any related issue and pull request numbers for future reference.

### CODE REVIEW

**Comment by bdice** [comment]
@bpuchala If you'd like, I'm happy to add your name to the [list of contributors](https://github.com/glotzerlab/signac-flow/blob/master/contributors.yaml). Let me know either way.

**Comment by bpuchala** [comment]
@bdice Sure, thanks!

**Review by syjlee — APPROVED** [review]

**Review by vyasr — APPROVED** [review]
I am fine with just centralizing for now without adding new tests.

Out of curiosity, in what scenario was `self.__class__.__name__` giving a different result from `self`?

**Comment by bdice** [comment]
> Out of curiosity, in what scenario was `self.__class__.__name__` giving a different result from `self`?

Not exactly sure, @bpuchala was using subclasses of FlowProject in some way.

**Comment by bpuchala** [comment]
It was giving "None" instead of "FlowProject" when running from a derived class. Here's an example of the issue, when run in a directory with an existing signac project:

Example:
```
import signac
import flow

# Add to flow.FlowProject:
#
# def _get_bundle_prefix(self):
#         sep = getattr(self._environment, "JOB_ID_SEPARATOR", "/")
#         return f"{self}{sep}bundle{sep}"

class MyFlowProject(flow.FlowProject):
    def __init__(self):
        signac_project = signac.init_project()
        super().__init__(signac_project.config)
        pass

my_proj = MyFlowProject()
print(my_proj._get_bundle_prefix())
```

Output:
```
$ python demo.py 
None/bundle/
```

**Comment by bdice** [comment]
Aha. This is pulling the signac.Project name from a defaulted config (we made project names optional in signac 1.8, and will be removing them in signac 2.0).

**Comment by bdice** [comment]
@bpuchala I think the more canonical way to do this is to leverage the fact that MyFlowProject inherits from FlowProject, which inherits from signac’s Project class. You can call MyFlowProject.init_project() and get the same method rather than feeding the config through manually.

**Pull request merged**
