### PR TITLE
Fix Expanse parallel gpu submission

### PR DESCRIPTION
**Pull request by cbkerr**
## Description

@Charlottez112 found that when she submitted a parallel gpu job on expanse, they didn't seem to run.

## Motivation and Context

She manually switched the mpiexec in the job script to mpirun and it worked, so we added it to the value of mpi_cmd in the ExpanseEnvironment.

She'll regenerate the template test

## Types of Changes

- [ ] Documentation update
- [x] Bug fix
- [ ] New feature
- [ ] Breaking change<sup>1</sup>

<sup>1</sup>The change breaks (or has the potential to break) existing functionality.

## Checklist:

- [ ] I am familiar with the [**Contributing Guidelines**](https://github.com/glotzerlab/signac-flow/blob/master/CONTRIBUTING.md).
- [ ] I agree with the terms of the [**Contributor Agreement**](https://github.com/glotzerlab/signac-flow/blob/master/ContributorAgreement.md).
- [ ] My name is on the [list of contributors](https://github.com/glotzerlab/signac-flow/blob/master/contributors.yaml).
- [ ] My code follows the [code style guideline](https://github.com/glotzerlab/signac-flow/blob/master/CONTRIBUTING.md#code-style) of this project.
- [ ] The changes introduced by this pull request are covered by existing or newly introduced tests.

If necessary:
- [ ] I have updated the API documentation as part of the package doc-strings.
- [ ] I have created a separate pull request to update the [framework documentation](https://docs.signac.io/) on [signac-docs](https://github.com/glotzerlab/signac-docs) and linked it here.
- [ ] I have updated the [changelog](https://github.com/glotzerlab/signac-flow/blob/master/changelog.txt).

### CODE REVIEW

**Comment by b-butler** [comment]
Hmmm :frowning_face: `mpiexec` is the standard launcher. It is annoying when you have to use a non-standard command (`mpirun`) to get this to work. Let me know when template tests have been changed. Also, has this been verified to work on both CPU and GPU nodes?

**Comment by cbkerr** [comment]
> Hmmm ☹️ `mpiexec` is the standard launcher. It is annoying when you have to use a non-standard command (`mpirun`) to get this to work. Let me know when template tests have been changed. Also, has this been verified to work on both CPU and GPU nodes?

btw we also crossed checked with https://glotzerlab-software.readthedocs.io/en/latest/clusters/expanse.html#gpu

@b-butler she just updated the template test

We've only tested parallel submission on gpu.

Still need to check:
- [ ] parallel submission on cpu.
- [ ] that parallel submission on gpu-shared still works as before
- [ ] that parallel submission on cpu-shared works

**Comment by joaander** [comment]
With the expanse openmpi 4.0.4 module, `mpiexec` and `mpirun` are symlinked to the same file:

```
[joaander@login01 ~]$ srun --partition=gpu-debug --pty --account=mia152 --ntasks-per-node=10 --nodes=1 --mem=96G --gpus=1 -t 00:30:00 --wait=0 --export=ALL /bin/bash
[joaander@exp-7-60 ~]$ module load gpu singularitypro openmpi/4.0.4
[joaander@exp-7-60 ~]$ ls -l `which mpiexec`
lrwxrwxrwx 1 mahidhar use300 7 Oct 12  2020 /cm/shared/apps/spack/gpu/opt/spack/linux-centos8-skylake_avx512/gcc-8.3.1/openmpi-4.0.4-mpm64p2fdhmmvnb5v2gszma2fsgdyu73/bin/mpiexec -> orterun
[joaander@exp-7-60 ~]$ ls -l `which mpirun`
lrwxrwxrwx 1 mahidhar use300 7 Oct 12  2020 /cm/shared/apps/spack/gpu/opt/spack/linux-centos8-skylake_avx512/gcc-8.3.1/openmpi-4.0.4-mpm64p2fdhmmvnb5v2gszma2fsgdyu73/bin/mpirun -> orterun
```
It is possible for the two to behave differently based on the name of the executable invoked, but I'd be surprised if one worked while the other didn't.

**Comment by Charlottez112** [comment]
> With the expanse openmpi 4.0.4 module, `mpiexec` and `mpirun` are symlinked to the same file:
> 
> ```
> [joaander@login01 ~]$ srun --partition=gpu-debug --pty --account=mia152 --ntasks-per-node=10 --nodes=1 --mem=96G --gpus=1 -t 00:30:00 --wait=0 --export=ALL /bin/bash
> [joaander@exp-7-60 ~]$ module load gpu singularitypro openmpi/4.0.4
> [joaander@exp-7-60 ~]$ ls -l `which mpiexec`
> lrwxrwxrwx 1 mahidhar use300 7 Oct 12  2020 /cm/shared/apps/spack/gpu/opt/spack/linux-centos8-skylake_avx512/gcc-8.3.1/openmpi-4.0.4-mpm64p2fdhmmvnb5v2gszma2fsgdyu73/bin/mpiexec -> orterun
> [joaander@exp-7-60 ~]$ ls -l `which mpirun`
> lrwxrwxrwx 1 mahidhar use300 7 Oct 12  2020 /cm/shared/apps/spack/gpu/opt/spack/linux-centos8-skylake_avx512/gcc-8.3.1/openmpi-4.0.4-mpm64p2fdhmmvnb5v2gszma2fsgdyu73/bin/mpirun -> orterun
> ```
> 
> It is possible for the two to behave differently based on the name of the executable invoked, but I'd be surprised if one worked while the other didn't.

I ran into this problem when I was still using the image I downloaded months ago. It worked on `gpu-shared` so I thought the same image should be working on the `gpu` partition. I'm not sure if this will still be a problem if I use the updated `expanse-gpu` image

**Comment by Charlottez112** [comment]
> @Charlottez112 could you share the pretend output of the submission that fails for you and elaborate on what behavior you get vs what you expect?

First of all, I was able to submit bundled parallel jobs to `gpu-shared` before, like your test. The problem was with the `gpu` partition.

I'm still using the old image I downloaded months ago.
```
(glotzer) [zshiqi@login02 md_nvt]$ python project.py submit --partition gpu --bundle=4 --parallel --pretend
Using environment configuration: ExpanseEnvironment
Querying scheduler...
Submitting cluster job 'md_nvt/bundle/5202e6153ead651bf98f7a43980d99f990e8183e':
 - Group: MD_simulation(836b22fe59fc5aea457ec494f876baf6)
 - Group: MD_simulation(742e1d834a9c1f9009176f886b014379)
 - Group: MD_simulation(3969880d6be57285ae3e819fcceaf645)
 - Group: MD_simulation(80b235059bd78312c675378cf1917606)
# Submit command: sbatch
#!/bin/bash
#SBATCH --job-name="md_nvt/bundle/5202e6153ead651bf98f7a43980d99f990e8183e"
#SBATCH --partition=gpu
#SBATCH -t 02:30:00

#SBATCH -N 1
#SBATCH --ntasks-per-node=4
#SBATCH --gpus=4
#SBATCH -A mia152

set -e
set -u

cd /expanse/lustre/scratch/zshiqi/temp_project/md_sim/md_nvt

# MD_simulation(836b22fe59fc5aea457ec494f876baf6)
/home/zshiqi/miniconda3/envs/glotzer/bin/python /expanse/lustre/scratch/zshiqi/temp_project/md_sim/md_nvt/project.py run -o MD_simulation -j 836b22fe59fc5aea457ec494f876baf6 &
# Eligible to run:
# mpiexec -n 1  singularity exec --nv /expanse/lustre/scratch/zshiqi/temp_project/hoomd_v2_software.sif python3 /expanse/lustre/scratch/zshiqi/temp_project/md_sim/md_nvt/project.py exec MD_simulation 836b22fe59fc5aea457ec494f876baf6

# MD_simulation(742e1d834a9c1f9009176f886b014379)
/home/zshiqi/miniconda3/envs/glotzer/bin/python /expanse/lustre/scratch/zshiqi/temp_project/md_sim/md_nvt/project.py run -o MD_simulation -j 742e1d834a9c1f9009176f886b014379 &
# Eligible to run:
# mpiexec -n 1  singularity exec --nv /expanse/lustre/scratch/zshiqi/temp_project/hoomd_v2_software.sif python3 /expanse/lustre/scratch/zshiqi/temp_project/md_sim/md_nvt/project.py exec MD_simulation 742e1d834a9c1f9009176f886b014379

# MD_simulation(3969880d6be57285ae3e819fcceaf645)
/home/zshiqi/miniconda3/envs/glotzer/bin/python /expanse/lustre/scratch/zshiqi/temp_project/md_sim/md_nvt/project.py run -o MD_simulation -j 3969880d6be57285ae3e819fcceaf645 &
# Eligible to run:
# mpiexec -n 1  singularity exec --nv /expanse/lustre/scratch/zshiqi/temp_project/hoomd_v2_software.sif python3 /expanse/lustre/scratch/zshiqi/temp_project/md_sim/md_nvt/project.py exec MD_simulation 3969880d6be57285ae3e819fcceaf645

# MD_simulation(80b235059bd78312c675378cf1917606)
/home/zshiqi/miniconda3/envs/glotzer/bin/python /expanse/lustre/scratch/zshiqi/temp_project/md_sim/md_nvt/project.py run -o MD_simulation -j 80b235059bd78312c675378cf1917606 &
# Eligible to run:
# mpiexec -n 1  singularity exec --nv /expanse/lustre/scratch/zshiqi/temp_project/hoomd_v2_software.sif python3 /expanse/lustre/scratch/zshiqi/temp_project/md_sim/md_nvt/project.py exec MD_simulation 80b235059bd78312c675378cf1917606
wait
```

Using this, I could submit the job, but it just didn't run. The entire output I got:
```
Using environment configuration: DefaultSlurmEnvironment
Using environment configuration: DefaultSlurmEnvironment
Using environment configuration: DefaultSlurmEnvironment
Using environment configuration: DefaultSlurmEnvironment
```
I know the job didn't run at all because no gsd or log files were generated.

Then I manually changed all the `mpiexec` to `mpirun`, and it worked.

**Comment by joaander** [comment]
@Charlottez112 I wouldn't expect that type of submission to execute correctly under any circumstances. At best, it would run all 4 simulations on GPU 0 very slowly - leaving GPUs 1,2, and 3 empty (while still being charged hours for their use).

Use aggregation so that the job submission requests N GPU tasks and launches them all with a single `mpiexec` command. This will distribute the work correctly to the multiple GPUs.

**Comment by Charlottez112** [comment]
> @Charlottez112 I wouldn't expect that type of submission to execute correctly under any circumstances. At best, it would run all 4 simulations on GPU 0 very slowly - leaving GPUs 1,2, and 3 empty (while still being charged hours for their use).
> 
I'm not sure I understand why exactly. From the documentation it seems like that should work, unless I misunderstood it.

**Comment by joaander** [comment]
> > @Charlottez112 I wouldn't expect that type of submission to execute correctly under any circumstances. At best, it would run all 4 simulations on GPU 0 very slowly - leaving GPUs 1,2, and 3 empty (while still being charged hours for their use).
> 
> I'm not sure I understand why exactly. From the documentation it seems like that should work, unless I misunderstood it.

Then the documentation is incorrect. See https://github.com/glotzerlab/signac-flow/issues/115#issuecomment-591533418

Signac bundles multiple processes via background processes using `&` in the shell script. This can be an effective way to run many CPU processes in parallel - provided that the OS schedules active threads to any available core. This is not the case on some HPC systems that aggressively bind processes to specific cores and assume that you will use an mpi launcher to execute your processes. In this case, all your bundled processes will use core 0.

For GPUs, the OS does not even attempt to schedule parallel processes on to multiple GPUs. It is up to the user to manually select which GPU to use. When you use aggregation, this process is automatic. There are manual methods, such as discussed in #455 - but these are error prone. Also, don't use `CUDA_VISIBLE_DEVICES` - some HPC centers will disable your account if you do. You can instead pass an id integer into your Python script and then pass that on to HOOMD to select a GPU.

I would *highly* recommend aggregation over the manual methods. The process is not prone to error and allows you to expand your bundles beyond single node jobs.

**Comment by Charlottez112** [comment]
> I would _highly_ recommend aggregation over the manual methods. The process is not prone to error and allows you to expand your bundles beyond single node jobs.

Thank you for the detailed explanation! I guess we'll need to update the documentation on this. Also, I've tried aggregation as you suggested, and it's indeed much faster - I didn't notice the fact that even though I requested 4 gpus, only one was used. Now I'm not sure if we still need to merge this PR becasue in most cases `mpiexec` seems to be working fine.

**Comment by cbkerr** [comment]
I started drafting changes to the documentation to de-emphasize the `--parallel` flag in https://github.com/glotzerlab/signac-docs/pull/157

**Comment by bdice** [comment]
@cbkerr @Charlottez112 I'm going to close this since it appears there is no issue with the template. If this is incorrect, please feel free to re-open. Thank you!

**Pull request closed without merging**
