### PR TITLE
adding ValueError when --job-name passed

### PR DESCRIPTION
**Pull request by ac-optimus**
## Description

fixes - #164
## Types of Changes

- [ ] Documentation update
- [x] Bug fix
- [ ] New feature
- [ ] Breaking change<sup>1</sup>

<sup>1</sup>The change breaks (or has the potential to break) existing functionality.

## Checklist:

- [x] I am familiar with the [**Contributing Guidelines**](https://github.com/glotzerlab/signac-flow/blob/master/CONTRIBUTING.md).
- [x] I agree with the terms of the [**Contributor Agreement**](https://github.com/glotzerlab/signac-flow/blob/master/ContributorAgreement.md).
- [ ] My name is on the [list of contributors](https://github.com/glotzerlab/signac-flow/blob/master/contributors.yaml).
- [x] My code follows the [code style guideline](https://github.com/glotzerlab/signac-flow/blob/master/CONTRIBUTING.md#code-style) of this project.
- [ ] The changes introduced by this pull request are covered by existing or newly introduced tests.

If necessary:
- [ ] I have updated the API documentation as part of the package doc-strings.
- [ ] I have created a separate pull request to update the [framework documentation](https://docs.signac.io/) on [signac-docs](https://github.com/glotzerlab/signac-docs) and linked it here.
- [x] I have updated the [changelog](https://github.com/glotzerlab/signac-flow/blob/master/changelog.txt).

### CODE REVIEW

**Comment by vyasr** [comment]
@atravitz @pepak13 to review this PR, I'd suggest that you install this version of flow on a cluster, try to submit a trivial job, and make sure that the error is caught.

**Comment by vyasr** [comment]
@ac-optimus could you update the Changelog and add an entry for your changes? Make sure to mention the relevant issue and PR numbers. Then I think this is good to go!

**Comment by ac-optimus** [comment]
> @ac-optimus could you update the Changelog and add an entry for your changes? Make sure to mention the relevant issue and PR numbers. Then I think this is good to go!

Done!

**Comment by vyasr** [comment]
Thanks! Just FYI, I made some minor edits. It looks like you took the version header straight out of the signac changelog including the version number, which isn't applicable here. We also don't add a version number until the release, we leave all pending changes under the "next" header. I also moved your PR under the Changed header since it's not really a new feature, just changing existing behavior in a sensible way.

**Comment by ac-optimus** [comment]
> Thanks! Just FYI, I made some minor edits. It looks like you took the version header straight out of the signac changelog including the version number, which isn't applicable here. We also don't add a version number until the release, we leave all pending changes under the "next" header. I also moved your PR under the Changed header since it's not really a new feature, just changing existing behavior in a sensible way.

ohh..okay, Thanks a lot!

**Pull request merged**
