### PR TITLE
Add project_class "wrapper" around test test_copy_conditions

### PR DESCRIPTION
**Pull request by b-butler**
## Description

Prevents future tests from breaking because the project's project_class attribute is changed.

## Motivation and Context

Since the `ProjectClassTest`'s `project_class` attribute is changed in the test function
`test_copy_conditions`, it needs to be reset at the end of the function to ensure that future
test beneath this one do not fail unexpectedly.

## Types of Changes

- [ ] Documentation update
- [ ] Bug fix
- [ ] New feature
- [ ] Breaking change<sup>1</sup>

<sup>1</sup>The change breaks (or has the potential to break) existing functionality.

## Checklist:

- [x] I am familiar with the [**Contributing Guidelines**](https://github.com/glotzerlab/signac-flow/blob/master/CONTRIBUTING.md).
- [x] I agree with the terms of the [**Contributor Agreement**](https://github.com/glotzerlab/signac-flow/blob/master/ContributorAgreement.md).
- [x] My name is on the [list of contributors](https://github.com/glotzerlab/signac-flow/blob/master/contributors.yaml).
- [x] My code follows the [code style guideline](https://github.com/glotzerlab/signac-flow/blob/master/CONTRIBUTING.md#code-style) of this project.
- [x] The changes introduced by this pull request are covered by existing or newly introduced tests.

If necessary:
- [ ] I have updated the API documentation as part of the package doc-strings.
- [ ] I have created a separate pull request to update the [framework documentation](https://docs.signac.io/) on [signac-docs](https://github.com/glotzerlab/signac-docs) and linked it here.
- [ ] I have updated the [changelog](https://github.com/glotzerlab/signac-flow/blob/master/changelog.txt).

### CODE REVIEW

**Comment by b-butler** [comment]
We could wrap all tests that change the test class to catch any error and restore the class's project class.

**Comment by vyasr** [comment]
Cleanest way to do that is probably create a separate test class for tests that do this and put the reassignment into the `setUp` and `tearDown` `unittest.TestCase` methods.

**Comment by csadorf** [comment]
> Cleanest way to do that is probably create a separate test class for tests that do this and put the reassignment into the `setUp` and `tearDown` `unittest.TestCase` methods.

I agree. @b-butler Could you update the PR to realize that?

**Comment by b-butler** [comment]
@vyasr and @csadorf The solution is fine, but that would cause those test to not be in the correct "conceptual" test class. If you are okay with that, then I am fine implementing it.

**Comment by csadorf** [comment]
I think that's fine. Alternatively, could we make the project class a function argument to `mock_project` ?

**Comment by b-butler** [comment]
@csadorf I think that is the proper solution. I have added a commit that does this and changed the relevant tests.

**Pull request merged**
