### PR TITLE
Enable copy_from and after conditions with multiple arguments.

### PR DESCRIPTION
**Pull request by csadorf**
## Description

Enable the provision of multiple operation functions as argument to `pre.after()` and `pre/post.copy_from()` 

## Motivation and Context

When generating operation functions programmatically, it is much more convenient to store those in a list and then we can use those lists as argument to the condition functions. Otherwise we cannot use the decorator syntax.

### Minimal example:
```python
def setup_foo(i):

    @Project.operation(f'foo-{i}')
    @Project.post.true(f'{foo_{i}')
    def foo(job):
        print(f"{i}th foo!")
        job.doc[f'foo_{i}'] = True

    return foo

foos = [setup_foo(i) for i in range(3)]

@Project.operation
@Project.pre.after(*foos)
def bar(job):
    print('all foos ran!')
```

**Without this feature** we would need to awkwardly call `Project.pre.after` as a function manually:
```python
for foo in foos:
    Project.pre.after(foo)(bar)
```

## Types of Changes

- [ ] Documentation update
- [ ] Bug fix
- [x] New feature
- [ ] Breaking change<sup>1</sup>

<sup>1</sup>The change breaks (or has the potential to break) existing functionality.

## Checklist:

- [x] I am familiar with the [**Contributing Guidelines**](https://github.com/glotzerlab/signac-flow/blob/master/CONTRIBUTING.md).
- [x] I agree with the terms of the [**Contributor Agreement**](https://github.com/glotzerlab/signac-flow/blob/master/ContributorAgreement.md).
- [x] My name is on the [list of contributors](https://github.com/glotzerlab/signac-flow/blob/master/contributors.yaml).
- [x] My code follows the [code style guideline](https://github.com/glotzerlab/signac-flow/blob/master/CONTRIBUTING.md#code-style) of this project.
- [x] The changes introduced by this pull request are covered by existing or newly introduced tests.

If necessary:
- [ ] I have updated the API documentation as part of the package doc-strings.
- [ ] I have created a separate pull request to update the [framework documentation](https://docs.signac.io/) on [signac-docs](https://github.com/glotzerlab/signac-docs) and linked it here.
- [ ] I have updated the [changelog](https://github.com/glotzerlab/signac-flow/blob/master/changelog.txt).

### CODE REVIEW

**Comment by csadorf** [comment]
@mikemhenry @vyasr Any chance you could review this PR soon? Or should I try to find someone else?

**Comment by vyasr** [comment]
I can review, I started going through all the issues/PRs associated with me yesterday and will get around to this one sometime today.

**Comment by csadorf** [comment]
> Nice feature. One note, depending on the sequence of the workflow you could end up evaluating conditions multiple times if they're conditions for multiple conditions passed to these decorators. However, not sure that there's a whole lot to be done about that, and it shouldn't matter except for massive projects.

I agree and I've created issue #125 to keep track of that.

**Comment by csadorf** [comment]
> Is it possible to add a unit test for this feature?

I've added a unit test to specifically test this feature.

**Comment by mikemhenry** [comment]
LGTM :tada:

**Comment by csadorf** [comment]
Thank's for the help @vyasr @mikemhenry @b-butler !

**Pull request merged**
