### PR TITLE
Fix inconsistant commandline arguments name.

### PR DESCRIPTION
**Pull request by b-butler**
## Description

Fixes inconsistent argument names in our command line API (in `exec`).
This relates to a positional argument, so I wouldn't consider this a breaking change.

## Types of Changes

- [ ] Documentation update
- [x] Bug fix
- [ ] New feature
- [ ] Breaking change<sup>1</sup>

<sup>1</sup>The change breaks (or has the potential to break) existing functionality.

## Checklist:

- [x] I am familiar with the [**Contributing Guidelines**](https://github.com/glotzerlab/signac-flow/blob/master/CONTRIBUTING.md).
- [x] I agree with the terms of the [**Contributor Agreement**](https://github.com/glotzerlab/signac-flow/blob/master/ContributorAgreement.md).
- [x] My name is on the [list of contributors](https://github.com/glotzerlab/signac-flow/blob/master/contributors.yaml).
- [x] My code follows the [code style guideline](https://github.com/glotzerlab/signac-flow/blob/master/CONTRIBUTING.md#code-style) of this project.
- [x] The changes introduced by this pull request are covered by existing or newly introduced tests.

If necessary:
- [ ] I have updated the API documentation as part of the package doc-strings.
- [ ] I have created a separate pull request to update the [framework documentation](https://docs.signac.io/) on [signac-docs](https://github.com/glotzerlab/signac-docs) and linked it here.
- [ ] I have updated the [changelog](https://github.com/glotzerlab/signac-flow/blob/master/changelog.txt).

### CODE REVIEW

**Review by bdice — APPROVED** [review]
I’m fine with this change. This change allows us to simplify #335.

**Comment by kidrahahjo** [comment]
I think that we should also allow the `--j` flag to be more consistent.

**Comment by b-butler** [comment]
@kidrahahjo in this case the desire CLI is `python3 project.py exec {op_name} {job_ids}`. Adding an optional argument that does the same as a previous positional one seems redundant. `exec` also requires at least one job so this would also not work well as a solely optional argument.

**Review by klywang — APPROVED** [review]
This looks good!

**Comment by kidrahahjo** [comment]
Aah, yes. I forgot about that point. Thanks for this!

**Pull request merged**
