### PR TITLE
Replace mode argument with partition

### PR DESCRIPTION
**Pull request by cbkerr**
## Description

Allows the user to specify the partition with the --partition flag like for other Slurm clusters.
## Motivation and Context

There was no way to submit to a GPU cluster on Great Lakes before this.

## Types of Changes

- [ ] Documentation update
- [x] Bug fix
- [ ] New feature
- [ ] Breaking change<sup>1</sup>

<sup>1</sup>The change breaks (or has the potential to break) existing functionality.

## Checklist:

- [x] I am familiar with the [**Contributing Guidelines**](https://github.com/glotzerlab/signac-flow/blob/master/CONTRIBUTING.md).
- [x] I agree with the terms of the [**Contributor Agreement**](https://github.com/glotzerlab/signac-flow/blob/master/ContributorAgreement.md).
- [x] My name is on the [list of contributors](https://github.com/glotzerlab/signac-flow/blob/master/contributors.yaml).
- [x] My code follows the [code style guideline](https://github.com/glotzerlab/signac-flow/blob/master/CONTRIBUTING.md#code-style) of this project.
- [ ] The changes introduced by this pull request are covered by existing or newly introduced tests.

If necessary:
- [ ] I have updated the API documentation as part of the package doc-strings.
- [ ] I have created a separate pull request to update the [framework documentation](https://docs.signac.io/) on [signac-docs](https://github.com/glotzerlab/signac-docs) and linked it here.
- [ ] I have updated the [changelog](https://github.com/glotzerlab/signac-flow/blob/master/changelog.txt).

### CODE REVIEW

**Comment by cbkerr** [comment]
Should we also allow the options for other Great Lakes partitions listed here?
https://arc-ts.umich.edu/greatlakes/rates/

**Comment by vyasr** [comment]
I would say that we don't need to support viz or debug, both of which are primarily for interactive purposes. Adding largemem is probably worthwhile.

**Comment by bdice** [comment]
What should happen if we request more GPUs than are available in one node? e.g. I would expect `nranks=24`, `ngpu=24` to give 12 nodes with 2 tasks per node (each node has 2 GPUs). Instead, it gives 24 tasks per node. This is important for MPI + multi-GPU communication.

```bash
#!/bin/bash
#SBATCH --job-name="aa16a1af-b00/7f3e901b/op_0/0000/8c81aafce7d9ae767f4f20809e2fdaf1"
#SBATCH --partition=gpu
#SBATCH --nodes=12
#SBATCH --ntasks-per-node=24
#SBATCH --gres=gpu:24

set -e
set -u

cd /tmp/tmpui7veles

# op_0(7f3e901b4266f28348b38721c099d612)
mpiexec -n 24 /home/bdice/miniconda3/envs/dice/bin/python ./interactive_template_test.py exec op_0 7f3e901b4266f28348b38721c099d612
```

I believe the Bridges-AI template may be a good example of how to handle this. When requesting more GPUs than are available on a GPU node, I think we want to split the CPU tasks across nodes correspondingly.

**Comment by vyasr** [comment]
I agree with @bdice that this is an issue that needs to be addressed in some way (perhaps in the proposed manner), but I think that is a separate issue and should be addressed independently. I'll open an issue for that, but this pull request can remain as is.

**Pull request merged**
