### PR TITLE
Show legend in all detailed-views.

### PR DESCRIPTION
**Pull request by csadorf**
Actually show legend in all detailed-status views.

### CODE REVIEW

**Comment by bdice** [comment]
@csadorf I might have misunderstood the problem. I thought `[S]` was not showing up because this line was removed. https://github.com/glotzerlab/signac-flow/pull/68/files#diff-896014ecae7b1581f5b837d124cdb4c9L771

**Comment by csadorf** [comment]
> @csadorf I might have misunderstood the problem. I thought `[S]` was not showing up because this line was removed. https://github.com/glotzerlab/signac-flow/pull/68/files#diff-896014ecae7b1581f5b837d124cdb4c9L771

I think there is some confusion here, because we use varies tables with various symbols. I don't have the mental capacity to sort this out right now.

**Comment by csadorf** [comment]
It might be worth it to wait until @zhou-pj has completed his work to address issue #67 .

**Comment by vyasr** [comment]
Yes, I was on the same page as Bradley regarding the problem here. @zhou-pj is making good progress, though, so I agree that we can maybe just punt on fixing this until he completes his work

**Pull request closed without merging**
