### PR TITLE
Fix --job-output command for all schedulers.

### PR DESCRIPTION
**Pull request by bdice**
## Description
User @salazardetroya noticed that the `--job-output` command wasn't supported by most environments. This PR makes it a universal feature for all schedulers.

*Reviewers:* should we split this up and have two commands for output and error instead of always combining them?

## Motivation and Context
Adds support for custom `--job-output` values.

## Types of Changes
- [ ] Documentation update
- [x] Bug fix
- [x] New feature
- [ ] Breaking change<sup>1</sup>

<sup>1</sup>The change breaks (or has the potential to break) existing functionality.

## Checklist:
- [x] I am familiar with the [**Contributing Guidelines**](https://github.com/glotzerlab/signac-flow/blob/master/CONTRIBUTING.md).
- [x] I agree with the terms of the [**Contributor Agreement**](https://github.com/glotzerlab/signac-flow/blob/master/ContributorAgreement.md).
- [x] My name is on the [list of contributors](https://github.com/glotzerlab/signac-flow/blob/master/contributors.yaml).
- [x] My code follows the [code style guideline](https://github.com/glotzerlab/signac-flow/blob/master/CONTRIBUTING.md#code-style) of this project.
- [ ] The changes introduced by this pull request are covered by existing or newly introduced tests.

If necessary:
- [x] I have updated the API documentation as part of the package doc-strings.
- [ ] I have created a separate pull request to update the [framework documentation](https://docs.signac.io/) on [signac-docs](https://github.com/glotzerlab/signac-docs) and linked it here.
- [x] I have updated the [changelog](https://github.com/glotzerlab/signac-flow/blob/master/changelog.txt).

### CODE REVIEW

**Comment by vyasr** [comment]
Part of the reason that we've punted on improving support for this feature in the past is that there are a couple gotchas to be aware of that should at least be documented:
- If users provide a relative path, what root directory is it relative to? Do we make any promises that it will always be relative to the project root? If not, are we exclusively recommending absolute paths? What should users who want to put outputs in the job directories do, and how could they construct appropriate absolute paths (if necessary)?
- How does this work with groups/bundles/aggregates?

I'm not a reviewer on this PR so I'll leave it to others to make final decisions, but answers to this question (at least in the form of documentation) are definitely in scope for this PR since adding this feature as is will likely lead to confusion without some attempt at providing an explanation.

I don't have a strong opinion on the separate vs. combined filename question. I would be fine with merging this PR without having that addressed, but IMO it's fine to just combine the streams for now.

**Review by atravitz — APPROVED** [review]
I think it's fine to leave things combined for now

**Review by Charlottez112 — APPROVED** [review]

**Comment by bdice** [comment]
@vyasr I'm not sure how you want to act on these answers to your questions. What else do you think needs to be done on this PR, if anything?

> If users provide a relative path, what root directory is it relative to? Do we make any promises that it will always be relative to the project root? If not, are we exclusively recommending absolute paths? What should users who want to put outputs in the job directories do, and how could they construct appropriate absolute paths (if necessary)?

This just sets the scheduler flags for output / error files. How the scheduler interprets paths is not something we have to worry about. I would guess that relatives paths are relative to the directory from which the submission command is executed.

> How does this work with groups/bundles/aggregates?

It doesn't. This is not job-specific. It just sets a scheduler flag for all the scripts being generated.

**Comment by tcmoore3** [comment]
Are there more changes that need to be made on this?

**Comment by bdice** [comment]
@tcmoore3 Nope, it's ready! Just lost track of this PR during my defense. Thanks for the reminder, I set it to merge once tests pass. 😄

**Pull request merged**
