### PR TITLE
change default environment from torque to slurm in umn.py template

### PR DESCRIPTION
**Pull request by ramanishsingh**
The UMN MSI is transitioning from torque to slurm scheduler. The template for the cluster had torque as the default environment (PR #353). This PR aims to change the default environment from torque to slurm.
## Description

Three files have been changed:
i) flow/environments/umn.py : torque --> slurm
ii) changelog.txt
iii) New tarball added : tests/template_reference_data.tar.gz
## Motivation and Context

This change will fix the template for UMN MSI cluster.

## Types of Changes

- [ ] Documentation update
- [ x] Bug fix
- [ ] New feature
- [ ] Breaking change<sup>1</sup>

<sup>1</sup>The change breaks (or has the potential to break) existing functionality.

## Checklist:

- [ x] I am familiar with the [**Contributing Guidelines**](https://github.com/glotzerlab/signac-flow/blob/master/CONTRIBUTING.md).
- [x ] I agree with the terms of the [**Contributor Agreement**](https://github.com/glotzerlab/signac-flow/blob/master/ContributorAgreement.md).
- [ x] My name is on the [list of contributors](https://github.com/glotzerlab/signac-flow/blob/master/contributors.yaml).
- [x ] My code follows the [code style guideline](https://github.com/glotzerlab/signac-flow/blob/master/CONTRIBUTING.md#code-style) of this project.
- [ x] The changes introduced by this pull request are covered by existing or newly introduced tests.

If necessary:
- [ ] I have updated the API documentation as part of the package doc-strings.
- [ ] I have created a separate pull request to update the [framework documentation](https://docs.signac.io/) on [signac-docs](https://github.com/glotzerlab/signac-docs) and linked it here.
- [ x] I have updated the [changelog](https://github.com/glotzerlab/signac-flow/blob/master/changelog.txt).

### CODE REVIEW

**Comment by ramanishsingh** [comment]
I used the following command to generate the tarball:
`python generate_template_reference_data.py -f`

**Comment by kidrahahjo** [comment]
@ramanishsingh It looks like the executable path on your machine didn't get mocked.
In `generate_template_reference_data.py` we have a method called `get_masked_flowproject` which we use to create the project. There we mock `sys.executable` before instantiating the project.

**Comment by bdice** [comment]
@kidrahahjo Thanks for finding that in the source, I didn't know exactly what to look for. 👍

@ramanishsingh I was able to run the template scripts on my local machine and it appears to have mocked the executable correctly. I'm interested in understanding the problem -- could you try to determine why the script isn't working on your machine? If our script has a bug, we can try to fix it. If you can't figure it out then I can push the corrected template data to your branch.

**Comment by ramanishsingh** [comment]
Thanks @kidrahahjo @bdice . I tried different Python versions, and also my local machine but everywhere I am facing the same issue. siganc-flow is working as expected on the cluster. @bdice please push the corrected template to the branch. Thanks!

**Comment by kidrahahjo** [comment]
@ramanishsingh I'm not sure about this but can you please check if the local python environment has the same signac-flow package installed which you use for development?

**Comment by ramanishsingh** [comment]
@kidrahahjo I made a new environment with conda and it is still giving the same error. I install signac-flow using `pip install -e .`. To check if the same signac-flow package is getting used, I uninstalled it first using pip and then tried `import flow` which gave me an error.

**Review by csadorf — COMMENTED** [review]
Looks fine overall 👍 Please ping me again when the test artifact was corrected.

**Comment by kidrahahjo** [comment]
@bdice @ramanishsingh I tried diving into this. It seems like this is a problem related to the `directives` module. We initialize `_EXECUTABLE` in that module with the default value of `sys.executable`. I think that value is stored before we mock `sys.executable` hence the default value of an executable always refers to the local environment.

For now, to get this PR merged, I will push the correct template and will try to resolve the issue in another PR

**Comment by kidrahahjo** [comment]
@ramanishsingh It looks like I don't have the permission to push the code in your branch. Can you please provide me with the necessary permissions?

**Comment by ramanishsingh** [comment]
@kidrahahjo  can you check if you have the necessary permissions now?

**Comment by kidrahahjo** [comment]
@ramanishsingh, since I'm not a maintainer, I believe I won't be able to push the code to your repository as I think you can only allow maintainers to edit your code.

**Comment by bdice** [comment]
@ramanishsingh Sorry, I might have made a mistake. I saw you pushed this commit, which I accidentally overwrote. It's no longer on the branch. https://github.com/glotzerlab/signac-flow/commit/8eb5b370048556a284fc51ce76b0506b03847dd4

```diff
diff --git a/flow/environment.py b/flow/environment.py
index dc5ea070..e2974da2 100644
--- a/flow/environment.py
+++ b/flow/environment.py
@@ -274,6 +274,8 @@ def get_prefix(cls, operation, parallel=False, mpi_prefix=None, cmd_prefix=None)
 
     @classmethod
     def _get_default_directives(cls):
+        import sys
+        _EXECUTABLE._default = sys.executable
         return _Directives(
             [
                 _NP,
```

I force-pushed because something wasn't working as I expected, which I thought was related to this PR being on your fork's `master` branch. Can you (or someone) confirm if the changes linked above fix the underlying issue? Also tagging @kidrahahjo because he was planning to file an issue about this.

**Comment by kidrahahjo** [comment]
@bdice I see the tests pass, we can merge this PR into master and I think we should handle the solution for the issue in another P.R. for which I filed an issue #398

**Review by bdice — APPROVED** [review]
I approve these changes. I agree with @kidrahahjo that we should solve issue #398 in a separate PR. This can be merged once it receives a second approving review -- pinging assigned reviewers @csadorf @yuanzhou0827 to take a look when convenient.

**Comment by ramanishsingh** [comment]
@bdice the temporary solution used here was proposed by @kidrahahjo . I used his suggestion to change environment.py temporarily, generate the new tarball, and again change environment.py to the original state. 

Thanks @bdice and @kidrahahjo

**Review by csadorf — APPROVED** [review]
Good to go! 🚢

**Pull request merged**
