### PR TITLE
Update pre-commit config

### PR DESCRIPTION
**Pull request by b-butler**
## Description
Updates pre-commit hooks to newer version of black.

## Checklist:

- [x] I am familiar with the [Contributing Guidelines](https://github.com/glotzerlab/signac-flow/blob/master/CONTRIBUTING.md).
- [x] I agree with the terms of the [Contributor Agreement](https://github.com/glotzerlab/signac-flow/blob/master/ContributorAgreement.md).
- [x] My name is on the [list of contributors](https://github.com/glotzerlab/signac-flow/blob/master/contributors.yaml).
- [x] The changes introduced by this pull request are covered by existing or newly introduced tests.
- [x] The [package documentation](https://github.com/glotzerlab/signac-flow/tree/master/doc) and [framework documentation](https://docs.signac.io/) in [signac-docs](https://github.com/glotzerlab/signac-docs) are up to date with these changes.
- [x] I have updated the [changelog](https://github.com/glotzerlab/signac-flow/blob/master/changelog.txt) and added any related issue and pull request numbers for future reference.

### CODE REVIEW

**Review by vyasr — COMMENTED** [review]
I'm confused. You seem to have updated the black version here, not isort?

**Comment by bdice** [comment]
Yes, #715 fixed the main problem. I did a similar fix for signac: https://github.com/glotzerlab/signac/pull/893

`pre-commit autoupdate` is what I recommend for any future PRs of a similar kind.

**Comment by vyasr** [comment]
@bdice I didn't notice that one, I think you and @b-butler get to fight over whether your PR merges or https://github.com/glotzerlab/signac/pull/894 :smile:

**Comment by b-butler** [comment]
@bdice that is what I ran, and @vyasr yeah it didn't change it because of #715. :joy: We can close this until the next automatic update.

**Review by bdice — APPROVED** [review]

**Comment by bdice** [comment]
I edited the description to indicate this updated black. Merging now. No need to wait for an autoupdate, this is fine.

**Pull request merged**
