### PR TITLE
Fix: tqdm.auto requires ipywidgets for notebook support.

### PR DESCRIPTION
**Pull request by bdice**
## Description
This is a workaround for half of the issue reported in #602:

> The notebook issue is partially caused by #371. tqdm has an automatic mode that detects if it is in a notebook, and shows an HTML progress bar instead of a console one (the console format doesn't render very well in the notebook, I have sometimes seen the `\r` fail to clear the current line and instead output lots of lines with progress bars). This issue has been reported to tqdm as https://github.com/tqdm/tqdm/issues/1082 and there is a PR https://github.com/tqdm/tqdm/pull/1218 to fix it by falling back to the console progress bar.

This PR does not change the default behavior of showing/not showing progress bars. See #602 for more details on that issue.

This workaround requires https://github.com/tqdm/tqdm/pull/1148, so the minimum tqdm version has been bumped to 4.60.0.

## Motivation and Context
Workaround for https://github.com/tqdm/tqdm/pull/1218

## Types of Changes
- [ ] Documentation update
- [x] Bug fix
- [ ] New feature
- [ ] Breaking change<sup>1</sup>

## Checklist:
- [x] I am familiar with the [**Contributing Guidelines**](https://github.com/glotzerlab/signac-flow/blob/master/CONTRIBUTING.md).
- [x] I agree with the terms of the [**Contributor Agreement**](https://github.com/glotzerlab/signac-flow/blob/master/ContributorAgreement.md).
- [x] My name is on the [list of contributors](https://github.com/glotzerlab/signac-flow/blob/master/contributors.yaml).
- [x] My code follows the [code style guideline](https://github.com/glotzerlab/signac-flow/blob/master/CONTRIBUTING.md#code-style) of this project.
- [ ] The changes introduced by this pull request are covered by existing or newly introduced tests.

If necessary:
- [ ] I have updated the API documentation as part of the package doc-strings.
- [ ] I have created a separate pull request to update the [framework documentation](https://docs.signac.io/) on [signac-docs](https://github.com/glotzerlab/signac-docs) and linked it here.
- [ ] I have updated the [changelog](https://github.com/glotzerlab/signac-flow/blob/master/changelog.txt).

### CODE REVIEW

**Comment by tommy-waltmann** [comment]
Since tqdm/tqdm#1218 and tqdm/tqdm#1148 are merged, shouldn't this PR just be a tqdm version bump? Or have they not made a release since fixing those bugs?

**Comment by bdice** [comment]
@tommy-waltmann That fix was made to tqdm after I created this PR. It doesn't look like tqdm 4.63.0 is out yet, which would include the fix. However, I'm also not sure if the "fix" acts like we want it to. We want to fall back silently to text-based progress bars if ipywidgets is not available. It seems like the changes made in tqdm will throw a warning that ipywidgets is not available. For now, I know this PR acts like I want (no warnings, just silent fallback from HTML to text progress bars).

**Review by tommy-waltmann — APPROVED** [review]
Fair enough, if you want different behavior than the `tqdm` default then you are going to have to wrap it somehow.

**Review by cbkerr — APPROVED** [review]
Thanks! The code makes sense and I checked with the tqdm docs.
I didn't test it locally.

**Pull request merged**
