### PR TITLE
Issue #175 add mpi_prefix to run

### PR DESCRIPTION
**Pull request by zhou-pj**
Draft PR

## Description
Issue #174 part two: add mpi_prefix to run

related issue #174, #184 and #175 

## Motivation and Context
This changes allow future change to allow run to access environment specific mpiexec

## Types of Changes

- [ ] Documentation update
- [ ] Bug fix
- [x] New feature
- [ ] Breaking change<sup>1</sup>

<sup>1</sup>The change breaks (or has the potential to break) existing functionality.

## Checklist:

- [x] I am familiar with the [**Contributing Guidelines**](https://github.com/glotzerlab/signac-flow/blob/master/CONTRIBUTING.md).
- [x] I agree with the terms of the [**Contributor Agreement**](https://github.com/glotzerlab/signac-flow/blob/master/ContributorAgreement.md).
- [x] My name is on the [list of contributors](https://github.com/glotzerlab/signac-flow/blob/master/contributors.yaml).
- [x] My code follows the [code style guideline](https://github.com/glotzerlab/signac-flow/blob/master/CONTRIBUTING.md#code-style) of this project.
- [ ] The changes introduced by this pull request are covered by existing or newly introduced tests.

If necessary:
- [ ] I have updated the API documentation as part of the package doc-strings.
- [ ] I have created a separate pull request to update the [framework documentation](https://docs.signac.io/) on [signac-docs](https://github.com/glotzerlab/signac-docs) and linked it here.
- [ ] I have updated the [changelog](https://github.com/glotzerlab/signac-flow/blob/master/changelog.txt).

### CODE REVIEW

**Comment by vyasr** [comment]
This should be merged after #184

**Comment by vyasr** [comment]
@zhou-pj I'm not exactly sure how you planned to structure your sequence of PRs here. Did you intend to make further changes to address #175 on this branch? I would recommend doing that, since this change doesn't make much sense to merge by itself IMO.

**Comment by zhou-pj** [comment]
@vyasr Sorry about the confusion, I have been thinking the two issue as one in my mind and forgot about the separately listed issue.... And yes this is meant to be for issue #175 and it is currently a draft, I intend to wait until PR #184 is finished and merged before keep working on this one.

**Comment by vyasr** [comment]
Sounds good, thanks for the update.

**Pull request closed without merging**
