### PR TITLE
Change default status_parallelization to "none".

### PR DESCRIPTION
**Pull request by bdice**
## Description
Changes status parallelization to "none".

Thread parallelism was causing bugs with GSD and deadlocks with signac 1.7 synced collections (those have been fixed).

Process parallelism is another viable strategy but the overhead in serialization/deserialization is currently too large to make the code performant unless the user's condition functions / labels are compute-bound.

Therefore, I have reverted to no parallelism for status checks. This seems to be performant enough on the project I've tested with around 2,000 jobs, 8 operations, and 15 condition functions.

@atravitz Can you verify that this fixes the issues you saw with GSD?

## Motivation and Context
The default status parallelization mode was changed from "process" to "thread" in a recent refactoring (#417). This caused some issues for user code. First it unveiled some problems with the locking mechanisms in signac (https://github.com/glotzerlab/signac/pull/529, https://github.com/glotzerlab/signac/pull/530), but also pointed to a lack of thread safety in [GSD](https://github.com/glotzerlab/gsd), which is a commonly used package with signac-flow. To avoid problems in user code, this PR changes the default back to "process" parallelization.

## Types of Changes

- [ ] Documentation update
- [x] Bug fix
- [ ] New feature
- [x] Breaking change<sup>1</sup>

<sup>1</sup>The change breaks (or has the potential to break) existing functionality.

## Checklist:
- [x] I am familiar with the [**Contributing Guidelines**](https://github.com/glotzerlab/signac-flow/blob/master/CONTRIBUTING.md).
- [x] I agree with the terms of the [**Contributor Agreement**](https://github.com/glotzerlab/signac-flow/blob/master/ContributorAgreement.md).
- [x] My name is on the [list of contributors](https://github.com/glotzerlab/signac-flow/blob/master/contributors.yaml).
- [x] My code follows the [code style guideline](https://github.com/glotzerlab/signac-flow/blob/master/CONTRIBUTING.md#code-style) of this project.
- [x] The changes introduced by this pull request are covered by existing or newly introduced tests.

If necessary:
- [ ] I have updated the API documentation as part of the package doc-strings.
- [ ] I have created a separate pull request to update the [framework documentation](https://docs.signac.io/) on [signac-docs](https://github.com/glotzerlab/signac-docs) and linked it here.
- [x] I have updated the [changelog](https://github.com/glotzerlab/signac-flow/blob/master/changelog.txt).

### CODE REVIEW

**Comment by bdice** [comment]
We have several reviewers on this PR - this can be merged once @atravitz (who saw the issues and reported on Slack) and at least one other reviewer approves.

**Comment by bdice** [comment]
Status performance tests are failing, which indicate that this change is making the code very slow. This means we have to benchmark/profile and figure out what's wrong. Related: #428

**Comment by mikemhenry** [comment]
Would you mind making another PR and seeing if serial passes? Then we can make that a new default

**Comment by bdice** [comment]
> 
> 
> Would you mind making another PR and seeing if serial passes? Then we can make that a new default

I just edited this PR title/description/content from "process" to "none" since that was easier.

**Comment by mikemhenry** [comment]
> I just edited this PR title/description/content from "process" to "none" since that was easier.

Sounds good! Looks like things are passing now!

**Review by klywang — APPROVED** [review]
Looks good!

**Review by Charlottez112 — APPROVED** [review]
Thank you for the change

**Pull request merged**
