### PR TITLE
Fix srun invocation on Great Lakes.

### PR DESCRIPTION
**Pull request by joaander**
## Description

Switch back to `mpirun` on Great Lakes.

## Motivation and Context

This change was made in #722. My workflows (`hoomd-validation`) work correctly with the most current release of flow, but not the `main` branch. When `flow` forks to `srun`, somehow my environment variables are all lost. For example, one of errors I got testing this was `singularity not found` even though I checked in the shell and singularity was in the PATH and the filesystem where singularity was stored was accessible.

Strangely, everything works if I directly called the srun command from the shell:
```
srun -n 4  /home/joaander/miniforge3/bin/python /gpfs/accounts/sglotzer_root/sglotzer0/joaander/hoomd-validation/hoomd_validation/project.py exec hard_disk_nvt_gpu agg-88ab2b6305a8b249743764fc16e5c22e
```

I don't know what causes this behavior, but the expedient solution is to switch back to `mpirun` which we have used for a long time on Great Lakes with fewer issues.

## Checklist:

- [x] I am familiar with the [Contributing Guidelines](https://github.com/glotzerlab/signac-flow/blob/main/CONTRIBUTING.md).
- [x] I agree with the terms of the [Contributor Agreement](https://github.com/glotzerlab/signac-flow/blob/main/ContributorAgreement.md).
- [x] My name is on the [list of contributors](https://github.com/glotzerlab/signac-flow/blob/main/contributors.yaml).
- [x] The changes introduced by this pull request are covered by existing or newly introduced tests.
- [ ] The [package documentation](https://github.com/glotzerlab/signac-flow/tree/main/doc) and [framework documentation](https://docs.signac.io/) in [signac-docs](https://github.com/glotzerlab/signac-docs) are up to date with these changes.
- [ ] I have updated the [changelog](https://github.com/glotzerlab/signac-flow/blob/main/changelog.txt) and added any related issue and pull request numbers for future reference.

### CODE REVIEW

**Comment by joaander** [comment]
Wait, this needs more testing on GPU nodes where srun configures the appropriate cgroups and mpirun does not. I may need to find a fix for the environment variable issue.

**Comment by joaander** [comment]
Upon further testing with a 4 V100 GPU job (which slurm assigned 3 GPUs to 1 node and 1 GPU to another node), `mpirun` assigns multiple tasks to the same GPU while `srun` correctly distributes the tasks. Note: we still need `--gpus-per-task` which I will add separately when working on #777.

I found that `srun --export=ALL` solved the environment variable forwarding issue. I also found that `srun` buffered stdout/stderr until the job completed, so I also added `-u` to disable buffering.

`srun -u --export=ALL` correctly runs `hoomd-validation` jobs both when hoomd is compiled from source and from the glotzerlab-software container. I am waiting for one more test on the 4 GPU A100 node.

**Comment by joaander** [comment]
This works on both V100 and A100 nodes on Great Lakes.

**Comment by joaander** [comment]
@b-butler This PR now includes both fixes to the Great Lakes environment necessary to make the template functional for the next release. 
* Use cpus-per-task to ensure all processes requested via np are placed on one node.
* Use gpus-per-task to allow multi-GPU jobs to correctly distribute to the assigned GPUs.

This formulation works only with homogenous jobs. How do I call `homogeneous_openmp_mpi_config` to ensure this?

I did not fix `--cpus-per-task` for all environments, as we are planning a more general fix in #777.

**Review by b-butler — APPROVED** [review]
I made some changes to the implementation (moving to the template) since we are refactoring and `nranks` will be removed. The code is equivalent.

**Pull request merged**
