### PR TITLE
Deprecate export_job_statuses

### PR DESCRIPTION
**Pull request by shandave**
## Description

Deprecated `export_job_statuses`
## Motivation and Context

Fixes part of #395 

## Types of Changes

- [ ] Documentation update
- [ ] Bug fix
- [x] New feature
- [ ] Breaking change<sup>1</sup>

<sup>1</sup>The change breaks (or has the potential to break) existing functionality.

## Checklist:

- [x] I am familiar with the [**Contributing Guidelines**](https://github.com/glotzerlab/signac-flow/blob/master/CONTRIBUTING.md).
- [x] I agree with the terms of the [**Contributor Agreement**](https://github.com/glotzerlab/signac-flow/blob/master/ContributorAgreement.md).
- [x] My name is on the [list of contributors](https://github.com/glotzerlab/signac-flow/blob/master/contributors.yaml).
- [x] My code follows the [code style guideline](https://github.com/glotzerlab/signac-flow/blob/master/CONTRIBUTING.md#code-style) of this project.
- [x] The changes introduced by this pull request are covered by existing or newly introduced tests.

If necessary:
- [ ] I have updated the API documentation as part of the package doc-strings.
- [ ] I have created a separate pull request to update the [framework documentation](https://docs.signac.io/) on [signac-docs](https://github.com/glotzerlab/signac-docs) and linked it here.
- [x] I have updated the [changelog](https://github.com/glotzerlab/signac-flow/blob/master/changelog.txt).

### CODE REVIEW

**Comment by shandave** [comment]
@bdice the tests passed locally, I'm not sure why they're failing here. Can you please help?

**Comment by vyasr** [comment]
@shandave the tests are actually passing, the problem is relating to code coverage. If you look at the list of tests, all the actual test runs (the ones that say CircleCI) are passing. The only test that's shown to be failing is Codecov (shown as codecov/project), which is a tool that we use to measure how much of the code base is used during tests. The idea with [code coverage](https://en.wikipedia.org/wiki/Code_coverage) is that if you have very few tests, or if you have many tests that only test a limited subset of the code base, then there are lots of areas that could break without tests ever failing because they're never tested. Unfortunately code coverage measurements tend to be a bit noisy, so small changes (plus or minus <1%) usually aren't meaningful. You don't need to worry about the change.

@tcmoore3 @pepak13 please review this when you get a chance!

**Comment by bdice** [comment]
@shandave Could you please add yourself to the [list of contributors](https://github.com/glotzerlab/signac-flow/blob/master/contributors.yaml) and add a deprecation notice to the [changelog](https://github.com/glotzerlab/signac-flow/blob/master/changelog.txt) (see previous examples from earlier versions)?

**Review by kidrahahjo — APPROVED** [review]
I had a chat with @shandave today, he will push the changes today!

**Comment by bdice** [comment]
@shandave @kidrahahjo This PR will be ready to merge as soon as the contributors/changelog are updated. Thanks!

**Review by bdice — APPROVED** [review]
@shandave Thank you! I'll merge this.

**Pull request merged**
