### PR TITLE
Feature/walltime budget

### PR DESCRIPTION
**Pull request by rosecers**
## Description
L2367-2410: Added a function to calculate the budget of CPU hours.

## Motivation and Context
#25 

## Types of Changes

- [ ] Documentation update
- [ ] Bug fix
- [X] New feature
- [ ] Breaking change<sup>1</sup>

This pull request is based on
- [ ] *master*, because it is a bug fix or an update to the documentation.
- [X] *develop*, because it introduces a new feature.

<sup>1</sup>The change breaks (or has the potential to break) existing functionality.

## Checklist:

- [X] I am familiar with the [**Contributing Guidelines**](https://github.com/glotzerlab/signac-flow/blob/master/CONTRIBUTING.md).
- [X] I agree with the terms of the [**Contributor Agreement**](https://github.com/glotzerlab/signac-flow/blob/master/ContributorAgreement.md).
- [X] My name is on the [list of contributors](https://github.com/glotzerlab/signac-flow/blob/master/contributors.yaml).
- [X] My code follows the [code style guideline](https://github.com/glotzerlab/signac-flow/blob/master/CONTRIBUTING.md#code-style) of this project.
- [X] The changes introduced by this pull request are covered by existing or newly introduced tests.

If necessary:
- [N/A] I have updated the API documentation as part of the package doc-strings.
- [N/A] I have created a separate pull request to update the [framework documentation](https://docs.signac.io/) on [signac-docs](https://github.com/glotzerlab/signac-docs) and linked it here.
- [X] I have updated the [changelog](https://github.com/glotzerlab/signac-flow/blob/master/changelog.txt).

### CODE REVIEW

**Comment by csadorf** [comment]
@rosecers I've rebased this branch on develop to only include the commits directly related to this pull request. Please follow these steps prior to adding additional commits to this branch:
```
git fetch --all
git checkout feature/walltime-budget
git reset --hard origin/feature/walltime-budget
```

**Comment by csadorf** [comment]
I believe this is more or less fine as is, the only question I have is how we integrate this with a potential `walltime` directive for operations moving forward. Currently this requires storing the walltime in the project document.

We could use a hierarchical approach, where we look up the walltime from the job document, then the project document, and then finally from a directive. @glotzerlab/signac-developers Thoughts?

**Comment by vyasr** [comment]
I don't think this necessarily conflicts with walltime directives, since we could just use a more descriptive name for this key (e.g. `expected_walltime` or `walltime_budget`). Having said that, I think that the approach you suggested makes sense; the directive is how much will be requested upon submission, so it should be the default expected value for estimation, but the user can override that by placing values in a job document.

**Comment by csadorf** [comment]
I am closing this for now until we have figure out how to properly define the walltime as part of the directives.

**Pull request closed without merging**
