### PR TITLE
Remove ntasks per node from GPU and GPU-shared

### LINKED ISSUE #588: Issue with Bridges2 template
### Description

There's an unneeded line in the Bridges2 template that causes Bridges2 to not correctly run when using a gpu because the --ntask-per-node command is not accepted by bridges2 when --gpus is also selected. 

### To reproduce

Run anything on bridges2 with a gpu selected:

--partition=GPU-shared 

Pretty sure the solution is just deleting the lines:

#SBATCH --ntasks-per-node={{ cpus_per_node }} 

in any of the GPU partitions. 

https://github.com/glotzerlab/signac-flow/blob/master/flow/templates/bridges2.sh

### Error output

Submission error: Error when calling submission command sbatch:
sbatch: error: Batch job submission failed: Requested node configuration is not available

### System configuration

Please complete the following information:

 - Operating System: Linux:
 - Version of Python [e.g. 3.7]:
 - Version of signac 1.6.0 :
 - Version of signac-flow 0.13.0 : 

Or copy & paste the output of: `python -c 'import platform; print(platform.platform()); import sys; print(sys.version); import signac; print(signac.__version__); import flow; print(flow.__version__)'`

### PR DESCRIPTION
**Pull request by cbkerr**
## Description

Solves a problem with a recent change to the bridges2 submission syntax.

## Motivation and Context

Resolves #588. See that issue for a nice writeup of the problem.

## Types of Changes

- [ ] Documentation update
- [x] Bug fix
- [ ] New feature
- [x] Breaking change<sup>1</sup>

<sup>1</sup>The change breaks (or has the potential to break) existing functionality.

I tested it by submitting with this branch in my workspace on bridges2, but only on GPU-shared.

## Checklist:

- [ ] I am familiar with the [**Contributing Guidelines**](https://github.com/glotzerlab/signac-flow/blob/master/CONTRIBUTING.md).
- [ ] I agree with the terms of the [**Contributor Agreement**](https://github.com/glotzerlab/signac-flow/blob/master/ContributorAgreement.md).
- [ ] My name is on the [list of contributors](https://github.com/glotzerlab/signac-flow/blob/master/contributors.yaml).
- [ ] My code follows the [code style guideline](https://github.com/glotzerlab/signac-flow/blob/master/CONTRIBUTING.md#code-style) of this project.
- [ ] The changes introduced by this pull request are covered by existing or newly introduced tests.

If necessary:
- [ ] I have updated the API documentation as part of the package doc-strings.
- [ ] I have created a separate pull request to update the [framework documentation](https://docs.signac.io/) on [signac-docs](https://github.com/glotzerlab/signac-docs) and linked it here.
- [ ] I have updated the [changelog](https://github.com/glotzerlab/signac-flow/blob/master/changelog.txt).

### CODE REVIEW

**Comment by bdice** [comment]
@cbkerr @Tobias-Dwyer @syjlee Before merging this PR, I would recommend investigating any potential effects with #583, which seems closely related.

**Comment by b-butler** [comment]
I don't think they are related from my examination today.

**Review by b-butler — APPROVED** [review]
:+1:

**Comment by b-butler** [comment]
@cbkerr you will need to update the template tests (see https://docs.signac.io/projects/flow/en/latest/support.html?highlight=template%20test#contributing-environments-to-the-package) for instructions on this.

**Review by b-butler — CHANGES_REQUESTED** [review]
I will approve again after template tests have been changed.

**Comment by vyasr** [comment]
FYI I updated the description/motivation to link this PR to the issue it's closing.

**Comment by vyasr** [comment]
@cbkerr you'll need to regenerate the template without the account. The easiest way is to temporarily remove the account from your signac config, but you could also pull this branch onto a different machine where you don't have the account and rerun the template generation script.

**Review by bdice — APPROVED** [review]
I updated the template tests again. This looks good to me if tests pass. Thanks @cbkerr for the fix and @Tobias-Dwyer for filing the issue. 👍

**Pull request merged**
