### PR TITLE
Resolve issue #142 by fixing error with zero jobs.

### LINKED ISSUE #142: Job profiler errors for projects with zero jobs
### Description

I have a project with zero jobs. The new built-in status profiler has a computation where it divides by `len(jobs)`, causing a division by zero error.

### To reproduce

Create an empty FlowProject and then run `python project.py status`.

### Error output

```
ERROR: Encountered error during program execution: 'float division by zero'
Execute with '--show-traceback' or '--debug' to get more information.
Traceback (most recent call last):
  File "project.py", line 25, in <module>
    Project().main()
  File "/home/bdice/code/signac-flow/flow/project.py", line 2870, in main
    _exit_or_raise()
  File "/home/bdice/code/signac-flow/flow/project.py", line 2838, in main
    args.func(args)
  File "/home/bdice/code/signac-flow/flow/project.py", line 2497, in _main_status
    delta_t = (time.time() - start) / len(jobs)
ZeroDivisionError: float division by zero
```

### System configuration

Please complete the following information:

 - Operating System [e.g. macOS]: 🐧
 - Version of Python [e.g. 3.7]: 3.7
 - Version of signac [e.g. 1.0]: current `master`
 - Version of signac-flow: current `master`

### PR DESCRIPTION
**Pull request by bdice**
## Description
Fixes issue with profiling project status when there are zero jobs.

## Motivation and Context
Resolves #142.

## Types of Changes
- [ ] Documentation update
- [x] Bug fix
- [ ] New feature
- [ ] Breaking change<sup>1</sup>

<sup>1</sup>The change breaks (or has the potential to break) existing functionality.

## Checklist:
- [x] I am familiar with the [**Contributing Guidelines**](https://github.com/glotzerlab/signac-flow/blob/master/CONTRIBUTING.md).
- [x] I agree with the terms of the [**Contributor Agreement**](https://github.com/glotzerlab/signac-flow/blob/master/ContributorAgreement.md).
- [x] My name is on the [list of contributors](https://github.com/glotzerlab/signac-flow/blob/master/contributors.yaml).
- [x] My code follows the [code style guideline](https://github.com/glotzerlab/signac-flow/blob/master/CONTRIBUTING.md#code-style) of this project.
- [ ] The changes introduced by this pull request are covered by existing or newly introduced tests.

If necessary:
- [ ] I have updated the API documentation as part of the package doc-strings.
- [ ] I have created a separate pull request to update the [framework documentation](https://docs.signac.io/) on [signac-docs](https://github.com/glotzerlab/signac-docs) and linked it here.
- [ ] I have updated the [changelog](https://github.com/glotzerlab/signac-flow/blob/master/changelog.txt).

### CODE REVIEW

**Comment by bdice** [comment]
This still shows the warning "took more than 0.2s per job" when I call status. I think this probably means that some kind of overhead time is taking more than 0.2s in total, since I replaced `len(jobs)` with `max(len(jobs), 1)`. I'm not sure how to address this -- feedback welcome.

**Comment by csadorf** [comment]
I'm surprised that I was the only one requested as reviewer for this PR by pull-assigner. Doesn't seem to work 100% yet?

**Comment by csadorf** [comment]
> This fix still shows the warning "took more than 0.2s per job" when I show the project status. I think this probably means that some kind of overhead time is taking more than 0.2s in total, since I replaced `len(jobs)` with `max(len(jobs), 1)`. I'm not sure how to address this -- feedback welcome.

@bdice I see the following alternative solutions:
1) Switch the threshold to an absolute value, something like 5 seconds or so. I think that's how git works when it suggests optimizations.
2) Increase the *per-job* threshold so that it doesn't trigger for so few jobs.
3) Use a function that accounts for the overhead of only very few jobs, e.g., by generally subtracting about 0.5 seconds or so.

**Comment by bdice** [comment]
@csadorf I like solutions 1 or 3.

**Comment by csadorf** [comment]
> @csadorf I like solutions 1 or 3.

Let's go with 3 then.

**Comment by vyasr** [comment]
I think option 3 is the right approach as well. A relative threshold is still what we want, but you don't want false positives from very small workspaces.

**Pull request merged**
