### PR TITLE
Update circle-ci tests to test against properly released version of signac-core

### PR DESCRIPTION
**Pull request by csadorf**
This has the benefit that we a) also test whether the installation works
and b) test against the respective latest patch release of that minor
release line.

## Types of Changes

- [ ] Documentation update
- [ ] Bug fix
- [ ] New feature
- [ ] Breaking change<sup>1</sup>

<sup>1</sup>The change breaks (or has the potential to break) existing functionality.

## Checklist:

- [x] I am familiar with the [**Contributing Guidelines**](https://github.com/glotzerlab/signac-flow/blob/master/CONTRIBUTING.md).
- [x] I agree with the terms of the [**Contributor Agreement**](https://github.com/glotzerlab/signac-flow/blob/master/ContributorAgreement.md).
- [x] My name is on the [list of contributors](https://github.com/glotzerlab/signac-flow/blob/master/contributors.yaml).
- [x] My code follows the [code style guideline](https://github.com/glotzerlab/signac-flow/blob/master/CONTRIBUTING.md#code-style) of this project.
- [x] The changes introduced by this pull request are covered by existing or newly introduced tests.

If necessary:
- [ ] I have updated the API documentation as part of the package doc-strings.
- [ ] I have created a separate pull request to update the [framework documentation](https://docs.signac.io/) on [signac-docs](https://github.com/glotzerlab/signac-docs) and linked it here.
- [ ] I have updated the [changelog](https://github.com/glotzerlab/signac-flow/blob/master/changelog.txt).

### CODE REVIEW

**Comment by csadorf** [comment]
Merge #346 after this one.

**Comment by csadorf** [comment]
In offline discussion with @bdice we determined that we should complement this change with a cron-job that tests integration compatibility between the signac and signac-flow main branches.

**Comment by vyasr** [comment]
Where will this cron job run?

**Comment by bdice** [comment]
@vyasr CircleCI supports scheduled jobs: https://circleci.com/docs/2.0/configuration-reference/#schedule

**Comment by vyasr** [comment]
Nice I wasn't aware of that feature. Sounds like a good plan to me, then.

**Comment by csadorf** [comment]
@bdice Are you still planning on implementing the cron job?

**Comment by bdice** [comment]
@csadorf Wasn't able to get it done over the weekend. I can work on it later this week but I'm having issues with my primary workstation today and can't get much development done. I'd prefer to finish/merge this PR and add the cron-like job later.

**Review by bdice — APPROVED** [review]
I'm going to merge this as-is and open a separate PR for the cron job.

**Pull request merged**
