### PR TITLE
WIP: Add a class for directives

### PR DESCRIPTION
**Pull request by b-butler**
## Description

Adds two classes `Directives` and `DirectivesItem` that serve as a smart mapping for environment and user specified directives and a specification for environmental directives respectively. `FlowProject` and `FlowGroup` have been changed accordingly.

## Motivation and Context

This addresses #265 and helps to centralize logic for directives.

## Types of Changes

- [ ] Documentation update
- [ ] Bug fix
- [x] New feature
- [ ] Breaking change<sup>1</sup>

<sup>1</sup>The change breaks (or has the potential to break) existing functionality.

## Checklist:

- [x] I am familiar with the [**Contributing Guidelines**](https://github.com/glotzerlab/signac-flow/blob/master/CONTRIBUTING.md).
- [x] I agree with the terms of the [**Contributor Agreement**](https://github.com/glotzerlab/signac-flow/blob/master/ContributorAgreement.md).
- [x] My name is on the [list of contributors](https://github.com/glotzerlab/signac-flow/blob/master/contributors.yaml).
- [x] My code follows the [code style guideline](https://github.com/glotzerlab/signac-flow/blob/master/CONTRIBUTING.md#code-style) of this project.
- [ ] The changes introduced by this pull request are covered by existing or newly introduced tests.

If necessary:
- [ ] I have updated the API documentation as part of the package doc-strings.
- [ ] I have created a separate pull request to update the [framework documentation](https://docs.signac.io/) on [signac-docs](https://github.com/glotzerlab/signac-docs) and linked it here.
- [ ] I have updated the [changelog](https://github.com/glotzerlab/signac-flow/blob/master/changelog.txt).

## Note
I plan on allowing a new contributor to take over this PR after having laid the backbone. I will continue to serve as an advisor for this PR though.

### CODE REVIEW

**Comment by b-butler** [comment]
What remains to be done is at least (there could be more)
* Test the individual `DirectivesItem`s.
* Test the `Directives` class.
* Determine and add environment specific `DirectivesItem` and correct their `get_default_directives` function (this at least at the decision level will likely involve a discussion between multiple people).
* Some probably large degree of code refactoring (I was just initially trying to get the outline working and there).
* Opening a PR in [signac-docs](https://github.com/glotzerlab/signac-docs) to update documentation.
* Going through docstrings and ensuring they are complete, grammatically correct, and helpful. Multiple methods will need these as well.
* Likely others.

**Comment by kidrahahjo** [comment]
As discussed with @b-butler, I will start writing tests to check the functionality of the new classes.

**Comment by csadorf** [comment]
@b-butler Is this PR work-in-progress? If yes, please prefix PR title with `WIP: `. In either case, do you want us to review now or later when more of the tasks have been completed?

**Comment by b-butler** [comment]
@csadorf a pass through the code in `flow/directives.py` would be helpful. I don't think a full review is warranted right now. But for anyone who wants to input on how the `Directives` class works, or how we deal with individual directives, it would be helpful to look now.

**Comment by kidrahahjo** [comment]
While testing I face a problem of importing the whole module. It's due to the `class directives` present in the `operations.py` module. Hence I need to explicitly import every method/class defined in `directives.py` module. This gets resolved if I change the name of the `directives.py` module. Should I do that?

**Comment by bdice** [comment]
@kidrahahjo A temporary workaround might be to add the line `from . import directives as _directives_module` in `__init__.py`. Then you can access those classes in `flow._directives_module`. I'm not sure what parts of this are intended to become "public" API, but this might help fix your immediate issues with testing.

**Comment by kidrahahjo** [comment]
> @kidrahahjo A temporary workaround might be to add the line `from . import directives as _directives_module` in `__init__.py`. Then you can access those classes in `flow._directives_module`. I'm not sure what parts of this are intended to become "public" API, but this might help fix your immediate issues with testing.

@bdice As a temporary solution, I decided to copy the global methods from `directives.py`. There were only 2-3 of them. And added something like `from .directives import _DirectivesItem, Directives, OnlyType` in `__init__.py`. I tried the way you suggested but it always referred to the `directives class` in `operations.py` module

**Comment by b-butler** [comment]
This is being moved to #283 for work by @kidrahahjo on a fork.

**Pull request closed without merging**
