### PR TITLE
Merge master into execution-hooks

### PR DESCRIPTION
**Pull request by klywang**
## Description
Merges `master` into `execution-hooks` (PR #189) and resolved merge conflicts with @cbkerr.

## Motivation and Context

`execution-hooks` was several commits behind the `master` branch.

## Types of Changes

- [ ] Documentation update
- [ ] Bug fix
- [ ] New feature
- [ ] Breaking change<sup>1</sup>

<sup>1</sup>The change breaks (or has the potential to break) existing functionality.

## Checklist:

- [x] I am familiar with the [**Contributing Guidelines**](https://github.com/glotzerlab/signac-flow/blob/master/CONTRIBUTING.md).
- [x] I agree with the terms of the [**Contributor Agreement**](https://github.com/glotzerlab/signac-flow/blob/master/ContributorAgreement.md).
- [x] My name is on the [list of contributors](https://github.com/glotzerlab/signac-flow/blob/master/contributors.yaml).
- [x] My code follows the [code style guideline](https://github.com/glotzerlab/signac-flow/blob/master/CONTRIBUTING.md#code-style) of this project.
- [x] The changes introduced by this pull request are covered by existing or newly introduced tests.

If necessary:
- [ ] I have updated the API documentation as part of the package doc-strings.
- [ ] I have created a separate pull request to update the [framework documentation](https://docs.signac.io/) on [signac-docs](https://github.com/glotzerlab/signac-docs) and linked it here.
- [ ] I have updated the [changelog](https://github.com/glotzerlab/signac-flow/blob/master/changelog.txt).

### CODE REVIEW

**Comment by vyasr** [comment]
I can handle reviewing this since I am (or at least I was) familiar with the implementation of the execution hooks. It will take me a few days, though.

**Comment by bdice** [comment]
It might be better to look at the diff with `master` instead of the diff with `execution-hooks`.

**Comment by kidrahahjo** [comment]
@bdice This is probably not the best place to discuss this but I think that we need a way to automatically set up a pre-commit hook for the developers when they install `siganc` or `signac-flow` for development. What do you think?

**Comment by vyasr** [comment]
@kidrahahjo I think it is possible but undesirable in a general setting to install git hooks automatically since it introduces a massive security loophole that could put off security-conscious users worried that we could be injecting arbitrary code into a `git clone/commit`. While this is probably not a serious concern for `signac`, it is probably why it's not done much in practice. `pre-commit install` is a 1-liner and I'd rather just have new contributors realize this is necessary when the CI checks fail.

@klywang @cbkerr in case you haven't gathered from @kidrahahjo's question, your PR is failing CI right now because your code violates a number of our style-related pre-checks. You will need to run `pre-commit install` locally, then you can do a `pre-commit run --all-files` to see what will fail. For starters, running `black` and `flake8` will get you most of the way there.

**Comment by vyasr** [comment]
As suggested by @bdice I've changed the targeted base branch to master here, I agree that it will be easier.

**Comment by cbkerr** [comment]
We didn't set the target branch to `master` because we wanted to preserve the unresolved conversations on #189 and keep the discussion on that page. We didn't want to push directly to `execution-hooks` in case we messed up the merge. 

I admit I didn't consider the formatting requirements because we were just trying to bring the `execution-hooks` branch up to the present.

If it looks like we did the merge correctly, we can push to `execution-hooks` and continue where that left off?

**Comment by bdice** [comment]
@cbkerr @vyasr Just to clarify, I meant that this PR would be easier to *review* by comparing its diff to master, even if it should be merged into (or replace) the previous execution hooks PR.

**Comment by vyasr** [comment]
@cbkerr @bdice yes sorry I just made a brief comment then started reviewing without clarifying. I just finished reviewing and the merge looks correct. I'm going to change the base branch back and merge, then let you fix the style there and we can continue conversations.

**Pull request merged**
