### PR TITLE
Fix multiline commands

### LINKED ISSUE #451: Submission scripts and multiline commands
### Description

Submission scripts do not account for multiline commands and the lines after the first are not commented.

### To reproduce
```
import flow
from flow import FlowProject

@FlowProject.operation
@flow.cmd
def mfe(job):
    simulation = ""
    for _ in range(3):
        simulation += "srun ./myprogram\n"
    return simulation

if __name__ == '__main__':
    FlowProject().main()
```
and
`python3 project.py submit -n 1 -o mfe --pretend`

### Error output
```
Using environment configuration: DefaultSlurmEnvironment
Querying scheduler...
Submitting cluster job 'gcmma/608970b404ca4dba7ce3cb21799bf592/mfe/f328dc68e8eee0a7565f4b4fb8e87312':
 - Group: mfe(608970b404ca4dba7ce3cb21799bf592)
#!/bin/bash
#SBATCH --job-name="gcmma/608970b404ca4dba7ce3cb21799bf592/mfe/f328dc68e8eee0a7565f4b4fb8e87312"
#SBATCH -t 12:00:00
#SBATCH --ntasks=1

set -e
set -u

cd /g/g92/miguel/code/topopt-gcmma

# mfe(608970b404ca4dba7ce3cb21799bf592)
/usr/WS2/miguel/firedrake/bin/python3 /g/g92/miguel/code/topopt-gcmma/project.py run -o mfe -j 608970b404ca4dba7ce3cb21799bf592
# Eligible to run:
# srun ./myprogram
srun ./myprogram
srun ./myprogram
```

### System configuration

Please complete the following information:

 - Operating System [e.g. macOS]: Linux
 - Version of Python [e.g. 3.7]: 3.7.0
 - Version of signac [e.g. 1.0]: 1.6.0
 - Version of signac-flow: 0.12.0

### PR DESCRIPTION
**Pull request by bdice**
## Description
Resolves #451 by adding support for multi-line commands.

I added a template reference script to help prevent regressions in this behavior.

## Motivation and Context
Resolves #451 from @salazardetroya.

## Types of Changes
- [ ] Documentation update
- [x] Bug fix
- [ ] New feature
- [ ] Breaking change<sup>1</sup>

<sup>1</sup>The change breaks (or has the potential to break) existing functionality.

## Checklist:

- [x] I am familiar with the [**Contributing Guidelines**](https://github.com/glotzerlab/signac-flow/blob/master/CONTRIBUTING.md).
- [x] I agree with the terms of the [**Contributor Agreement**](https://github.com/glotzerlab/signac-flow/blob/master/ContributorAgreement.md).
- [x] My name is on the [list of contributors](https://github.com/glotzerlab/signac-flow/blob/master/contributors.yaml).
- [x] My code follows the [code style guideline](https://github.com/glotzerlab/signac-flow/blob/master/CONTRIBUTING.md#code-style) of this project.
- [x] The changes introduced by this pull request are covered by existing or newly introduced tests.

If necessary:
- [ ] I have updated the API documentation as part of the package doc-strings.
- [ ] I have created a separate pull request to update the [framework documentation](https://docs.signac.io/) on [signac-docs](https://github.com/glotzerlab/signac-docs) and linked it here.
- [x] I have updated the [changelog](https://github.com/glotzerlab/signac-flow/blob/master/changelog.txt).

### CODE REVIEW

**Comment by salazardetroya** [comment]
This works for me, thanks!

**Comment by bdice** [comment]
@tcmoore3 @cbkerr This fix will be ready to merge once it receives a review. Thanks!

**Review by cbkerr — APPROVED** [review]
Looks good to me. What is the `template_reference_data.tar.gz` file for?

**Review by tcmoore3 — APPROVED** [review]

**Comment by kidrahahjo** [comment]
> Looks good to me. What is the `template_reference_data.tar.gz` file for?

@cbkerr this file helps us to test submission scripts regressively. If you see `test_templates.py` module, we generate the templates using code and then equate it with already stored templates in a zipped file `template_reference_data.tar.gz`.

So, when we make any change to the code which effects submission script, in order to test what we wrote, we regenerate the submission scripts and zip them using tests/generate_template_reference_data.py` module.

**Pull request merged**
